# Generated by Django 6.0.7 on 2026-07-30

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import integrations.models
from common.rls import get_disable_policy_sql, get_enable_policy_sql

TABLES = (
    "integration_facebook_conversion_settings",
    "integration_facebook_conversion_event",
)


def enable_conversion_rls(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    with schema_editor.connection.cursor() as cursor:
        for table in TABLES:
            cursor.execute(get_enable_policy_sql(table))


def disable_conversion_rls(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    with schema_editor.connection.cursor() as cursor:
        for table in reversed(TABLES):
            cursor.execute(get_disable_policy_sql(table))


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0029_delete_sessiontoken"),
        ("integrations", "0002_facebook_oauth_session"),
        ("leads", "0013_lead_custom_fields"),
        ("sdr", "0010_ses_delivery_feedback"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FacebookConversionSettings",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        verbose_name="Last Modified At",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("is_enabled", models.BooleanField(default=False)),
                ("pixel_id", models.CharField(blank=True, max_length=32)),
                ("access_token_ciphertext", models.TextField(blank=True)),
                ("access_token_hint", models.CharField(blank=True, max_length=12)),
                (
                    "lead_event_source",
                    models.CharField(default="BottleCRM", max_length=100),
                ),
                (
                    "raw_lead_event_name",
                    models.CharField(default="RawLead", max_length=100),
                ),
                (
                    "qualified_lead_event_name",
                    models.CharField(
                        default="MarketingQualifiedLead",
                        max_length=100,
                    ),
                ),
                (
                    "converted_event_name",
                    models.CharField(default="Converted", max_length=100),
                ),
                (
                    "qualified_bands",
                    models.JSONField(
                        blank=True,
                        default=integrations.models.default_facebook_qualified_bands,
                    ),
                ),
                ("test_event_code", models.CharField(blank=True, max_length=100)),
                ("last_event_sent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "org",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="facebook_conversion_settings",
                        to="common.org",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Last Modified By",
                    ),
                ),
            ],
            options={"db_table": "integration_facebook_conversion_settings"},
        ),
        migrations.CreateModel(
            name="FacebookConversionEvent",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        verbose_name="Last Modified At",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("leadgen_id", models.CharField(max_length=32)),
                ("event_name", models.CharField(max_length=100)),
                ("event_key", models.CharField(max_length=160)),
                ("event_time", models.DateTimeField()),
                ("pixel_id", models.CharField(max_length=32)),
                ("lead_event_source", models.CharField(max_length=100)),
                ("test_event_code", models.CharField(blank=True, max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sent", "Sent"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                (
                    "provider_events_received",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("provider_trace_id", models.CharField(blank=True, max_length=255)),
                ("error_code", models.CharField(blank=True, max_length=80)),
                ("error_message", models.CharField(blank=True, max_length=1000)),
                ("last_attempted_at", models.DateTimeField(blank=True, null=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "crm_lead",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="facebook_conversion_events",
                        to="leads.lead",
                    ),
                ),
                (
                    "intake",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="facebook_conversion_events",
                        to="sdr.leadintake",
                    ),
                ),
                (
                    "org",
                    models.ForeignKey(
                        help_text="Organization this record belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="common.org",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Last Modified By",
                    ),
                ),
            ],
            options={
                "db_table": "integration_facebook_conversion_event",
                "ordering": ("-event_time", "-created_at"),
                "indexes": [
                    models.Index(
                        fields=["org", "status", "-event_time"],
                        name="fb_conversion_org_status_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("org", "event_key"),
                        name="unique_fb_conversion_event_key",
                    )
                ],
            },
        ),
        migrations.RunPython(enable_conversion_rls, disable_conversion_rls),
    ]
