# Generated by Django 6.0.7 on 2026-07-30

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

from common.rls import get_disable_policy_sql, get_enable_policy_sql


def enable_messenger_rls(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(get_enable_policy_sql("integration_facebook_messenger_message"))


def disable_messenger_rls(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(get_disable_policy_sql("integration_facebook_messenger_message"))


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0029_delete_sessiontoken"),
        ("integrations", "0003_facebook_conversion_feedback"),
        ("sdr", "0011_facebook_messenger_intake"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="facebookpageconnection",
            name="last_message_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="facebookpageconnection",
            name="messenger_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="FacebookMessengerMessage",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        verbose_name="Last Modified At",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("page_id", models.CharField(max_length=64)),
                ("sender_psid", models.CharField(max_length=128)),
                ("message_id", models.CharField(max_length=255)),
                ("body", models.TextField(blank=True)),
                ("attachment_types", models.JSONField(blank=True, default=list)),
                ("occurred_at", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("received", "Received"),
                            ("queued", "Queued"),
                            ("processed", "Processed"),
                            ("ignored", "Ignored"),
                            ("failed", "Failed"),
                        ],
                        default="received",
                        max_length=16,
                    ),
                ),
                ("error_code", models.CharField(blank=True, max_length=80)),
                ("error_message", models.CharField(blank=True, max_length=1000)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "connection",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="messenger_messages",
                        to="integrations.facebookpageconnection",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "intake",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="facebook_messenger_messages",
                        to="sdr.leadintake",
                    ),
                ),
                (
                    "org",
                    models.ForeignKey(
                        help_text="Organization this record belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="common.org",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Last Modified By",
                    ),
                ),
            ],
            options={
                "db_table": "integration_facebook_messenger_message",
                "ordering": ("-occurred_at", "-created_at"),
                "indexes": [
                    models.Index(
                        fields=["org", "status", "-occurred_at"],
                        name="fb_messenger_org_status_idx",
                    ),
                    models.Index(
                        fields=["org", "page_id", "sender_psid"],
                        name="fb_messenger_sender_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("org", "page_id", "message_id"),
                        name="unique_fb_messenger_message",
                    )
                ],
            },
        ),
        migrations.RunPython(enable_messenger_rls, disable_messenger_rls),
    ]
