# Generated by Django 6.0.7 on 2026-07-30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("integrations", "0005_facebook_messenger_auto_reply"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="facebookmessengerreply",
            name="unique_fb_messenger_auto_reply",
        ),
        migrations.AlterField(
            model_name="facebookmessengerreply",
            name="trigger_message",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="outbound_replies",
                to="integrations.facebookmessengermessage",
            ),
        ),
        migrations.AddField(
            model_name="facebookmessengerreply",
            name="client_request_id",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="facebookmessengerreply",
            name="kind",
            field=models.CharField(
                choices=[
                    ("auto_acknowledgement", "Auto acknowledgement"),
                    ("manual", "Manual"),
                ],
                default="auto_acknowledgement",
                max_length=32,
            ),
        ),
        migrations.AddConstraint(
            model_name="facebookmessengerreply",
            constraint=models.UniqueConstraint(
                condition=models.Q(kind="auto_acknowledgement"),
                fields=("org", "page_id", "recipient_psid"),
                name="unique_fb_messenger_auto_reply",
            ),
        ),
        migrations.AddConstraint(
            model_name="facebookmessengerreply",
            constraint=models.UniqueConstraint(
                condition=models.Q(client_request_id__isnull=False),
                fields=("org", "client_request_id"),
                name="unique_fb_messenger_reply_request",
            ),
        ),
    ]
