# Generated by Django 6.0.7 on 2026-08-12 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0029_delete_sessiontoken"),
        ("integrations", "0008_whatsapp_rls"),
    ]

    operations = [
        migrations.AlterField(
            model_name="whatsappbusinessconnection",
            name="org",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="whatsapp_business_connection",
                to="common.org",
            ),
        ),
    ]
