# Generated by Django 6.0.7 on 2026-08-12 12:52

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

from common.rls import get_disable_policy_sql, get_enable_policy_sql

TABLES = (
    "integration_linkedin_connection",
    "integration_linkedin_invitation",
)


def enable_linkedin_rls(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    with schema_editor.connection.cursor() as cursor:
        for table in TABLES:
            cursor.execute(get_enable_policy_sql(table))


def disable_linkedin_rls(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    with schema_editor.connection.cursor() as cursor:
        for table in reversed(TABLES):
            cursor.execute(get_disable_policy_sql(table))


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0029_delete_sessiontoken'),
        ('integrations', '0010_apolloconnection'),
        ('sdr', '0019_sdroutboundcampaign_linkedin_invitation_message'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkedInConnection',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('access_token_ciphertext', models.TextField()),
                ('access_token_hint', models.CharField(blank=True, max_length=12)),
                ('is_active', models.BooleanField(default=False)),
                ('partner_access_confirmed', models.BooleanField(default=False)),
                ('last_invitation_sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('org', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='linkedin_connection', to='common.org')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
            ],
            options={
                'db_table': 'integration_linkedin_connection',
            },
        ),
        migrations.CreateModel(
            name='LinkedInInvitation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('campaign_run', models.PositiveIntegerField()),
                ('recipient', models.EmailField(max_length=254)),
                ('message_body', models.CharField(blank=True, max_length=300)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('queued', 'Queued'), ('sending', 'Sending'), ('sent', 'Sent'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending', max_length=16)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('provider_invitation_id', models.CharField(blank=True, max_length=255)),
                ('error_code', models.CharField(blank=True, max_length=80)),
                ('error_message', models.CharField(blank=True, max_length=1000)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('provider_status_snapshot', models.JSONField(blank=True, default=dict)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linkedin_invitations', to='sdr.sdroutboundcampaign')),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invitations', to='integrations.linkedinconnection')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('org', models.ForeignKey(help_text='Organization this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='common.org')),
                ('prospect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linkedin_invitations', to='sdr.sdroutboundprospect')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
            ],
            options={
                'db_table': 'integration_linkedin_invitation',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='linkedinconnection',
            index=models.Index(fields=['org', 'is_active'], name='integration_org_id_6501c7_idx'),
        ),
        migrations.AddIndex(
            model_name='linkedininvitation',
            index=models.Index(fields=['org', 'status', '-created_at'], name='li_invite_org_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='linkedininvitation',
            constraint=models.UniqueConstraint(fields=('org', 'campaign', 'prospect', 'campaign_run'), name='unique_li_campaign_invitation'),
        ),
        migrations.AddConstraint(
            model_name='linkedininvitation',
            constraint=models.UniqueConstraint(condition=models.Q(('provider_invitation_id', ''), _negated=True), fields=('org', 'provider_invitation_id'), name='unique_li_provider_invitation'),
        ),
        migrations.RunPython(enable_linkedin_rls, disable_linkedin_rls),
    ]
