# Generated by Django 6.0.7 on 2026-08-29 14:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


SECURITY_SQL = r"""
ALTER TABLE integration_feishu_base_person_import ENABLE ROW LEVEL SECURITY;
ALTER TABLE integration_feishu_base_person_import FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS org_isolation ON integration_feishu_base_person_import;
DROP POLICY IF EXISTS org_insert_check ON integration_feishu_base_person_import;
CREATE POLICY org_isolation ON integration_feishu_base_person_import
FOR ALL USING (
    org_id::text = (SELECT NULLIF(current_setting('app.current_org', true), ''))
);
CREATE POLICY org_insert_check ON integration_feishu_base_person_import
FOR INSERT WITH CHECK (
    org_id::text = (SELECT NULLIF(current_setting('app.current_org', true), ''))
);

CREATE OR REPLACE FUNCTION integration_validate_feishu_base_person_import_scope()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
    bound_job automation_job%ROWTYPE;
BEGIN
    IF TG_OP = 'UPDATE' AND (
        OLD.org_id IS DISTINCT FROM NEW.org_id
        OR OLD.connection_id IS DISTINCT FROM NEW.connection_id
        OR OLD.requested_by_id IS DISTINCT FROM NEW.requested_by_id
        OR OLD.execution_request_id IS DISTINCT FROM NEW.execution_request_id
        OR OLD.mapping_ciphertext IS DISTINCT FROM NEW.mapping_ciphertext
        OR OLD.mapping_sha256 IS DISTINCT FROM NEW.mapping_sha256
        OR OLD.destination_sha256 IS DISTINCT FROM NEW.destination_sha256
        OR OLD.source_namespace IS DISTINCT FROM NEW.source_namespace
        OR OLD.row_limit IS DISTINCT FROM NEW.row_limit
        OR (
            OLD.automation_job_id IS NOT NULL
            AND OLD.automation_job_id IS DISTINCT FROM NEW.automation_job_id
        )
        OR (
            OLD.import_batch_id IS NOT NULL
            AND OLD.import_batch_id IS DISTINCT FROM NEW.import_batch_id
        )
    ) THEN
        RAISE EXCEPTION 'Feishu Base person import immutable binding changed'
            USING ERRCODE = '23514';
    END IF;
    IF NOT EXISTS (
        SELECT 1 FROM integration_feishu_base_connection
        WHERE id = NEW.connection_id AND org_id = NEW.org_id
    ) THEN
        RAISE EXCEPTION 'Feishu Base person import connection mismatch'
            USING ERRCODE = '23514';
    END IF;
    IF NOT EXISTS (
        SELECT 1 FROM profile
        WHERE id = NEW.requested_by_id AND org_id = NEW.org_id
    ) THEN
        RAISE EXCEPTION 'Feishu Base person import requester mismatch'
            USING ERRCODE = '23514';
    END IF;
    IF NOT EXISTS (
        SELECT 1 FROM integration_external_execution_request
        WHERE id = NEW.execution_request_id
          AND org_id = NEW.org_id
          AND channel = 'feishu'
          AND action = 'import_person_records'
    ) THEN
        RAISE EXCEPTION 'Feishu Base person import execution mismatch'
            USING ERRCODE = '23514';
    END IF;
    IF NEW.automation_job_id IS NOT NULL THEN
        SELECT * INTO bound_job FROM automation_job
        WHERE id = NEW.automation_job_id AND org_id = NEW.org_id;
        IF NOT FOUND
           OR bound_job.name <> 'integrations.feishu_base_person_import'
           OR jsonb_object_length(bound_job.payload) <> 2
           OR bound_job.payload ->> 'import_id' <> NEW.id::text
           OR bound_job.payload ->> 'execution_request_id' <> NEW.execution_request_id::text
        THEN
            RAISE EXCEPTION 'Feishu Base person import job mismatch'
                USING ERRCODE = '23514';
        END IF;
    END IF;
    IF NEW.import_batch_id IS NOT NULL AND NOT EXISTS (
        SELECT 1 FROM matching_person_import_batch
        WHERE id = NEW.import_batch_id
          AND org_id = NEW.org_id
          AND source = 'feishu'
          AND source_namespace = NEW.source_namespace
    ) THEN
        RAISE EXCEPTION 'Feishu Base person import batch mismatch'
            USING ERRCODE = '23514';
    END IF;
    IF NEW.status = 'previewed' AND NEW.import_batch_id IS NULL THEN
        RAISE EXCEPTION 'Previewed Feishu Base import requires a batch'
            USING ERRCODE = '23514';
    END IF;
    RETURN NEW;
END;
$$;

CREATE TRIGGER integration_feishu_base_person_import_scope_guard
BEFORE INSERT OR UPDATE ON integration_feishu_base_person_import
FOR EACH ROW EXECUTE FUNCTION integration_validate_feishu_base_person_import_scope();
"""


DROP_SECURITY_SQL = r"""
DROP TRIGGER IF EXISTS integration_feishu_base_person_import_scope_guard
    ON integration_feishu_base_person_import;
DROP FUNCTION IF EXISTS integration_validate_feishu_base_person_import_scope();
"""


def install_security(apps, schema_editor):
    if schema_editor.connection.vendor != 'postgresql':
        return
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(SECURITY_SQL)


def remove_security(apps, schema_editor):
    if schema_editor.connection.vendor != 'postgresql':
        return
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(DROP_SECURITY_SQL)


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0001_initial'),
        ('common', '0030_profile_matching_access_level'),
        ('integrations', '0016_protect_feishu_base_sync_intake'),
        ('matching', '0009_scrub_terminal_import_staging'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeishuBasePersonImport',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('reading', 'Reading provider records'), ('previewed', 'Preview ready'), ('failed', 'Failed'), ('unknown', 'Unknown read or local outcome')], default='queued', max_length=24)),
                ('mapping_ciphertext', models.TextField()),
                ('mapping_sha256', models.CharField(max_length=64)),
                ('destination_sha256', models.CharField(max_length=64)),
                ('source_namespace', models.CharField(max_length=128)),
                ('row_limit', models.PositiveSmallIntegerField(default=100)),
                ('attempt_count', models.PositiveSmallIntegerField(default=0)),
                ('total_count', models.PositiveIntegerField(default=0)),
                ('ready_count', models.PositiveIntegerField(default=0)),
                ('invalid_count', models.PositiveIntegerField(default=0)),
                ('error_code', models.CharField(blank=True, max_length=80)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('automation_job', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='feishu_base_person_import', to='automation.automationjob')),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='person_imports', to='integrations.feishubaseconnection')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('execution_request', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='feishu_base_person_import', to='integrations.externalexecutionrequest')),
                ('import_batch', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='feishu_base_import', to='matching.personimportbatch')),
                ('org', models.ForeignKey(help_text='Organization this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='common.org')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requested_feishu_base_person_imports', to='common.profile')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
            ],
            options={
                'db_table': 'integration_feishu_base_person_import',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['org', 'status', '-created_at'], name='feishu_import_org_status_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='feishubasepersonimport',
            constraint=models.CheckConstraint(
                condition=models.Q(('row_limit__gte', 1), ('row_limit__lte', 500)),
                name='feishu_import_row_limit_valid',
            ),
        ),
        migrations.AddConstraint(
            model_name='feishubasepersonimport',
            constraint=models.CheckConstraint(
                condition=models.Q(('status', 'previewed'), _negated=True)
                | models.Q(('import_batch__isnull', False)),
                name='feishu_import_preview_has_batch',
            ),
        ),
        migrations.RunPython(install_security, remove_security),
    ]
