from django.urls import path

from integrations.api.views import (
    ApolloConnectionView,
    FacebookConversionSettingsView,
    FacebookMessengerConversationView,
    FacebookOAuthCallbackView,
    FacebookOAuthPageSelectionView,
    FacebookOAuthSessionView,
    FacebookOAuthStartView,
    FacebookPageConnectionDetailView,
    FacebookPageConnectionListCreateView,
    FacebookWebhookView,
    FeishuBaseConnectionTestView,
    FeishuBaseConnectionView,
    LinkedInConnectionView,
    WhatsAppBusinessConnectionView,
    WhatsAppWebhookView,
)

app_name = "api_integrations"

urlpatterns = [
    path(
        "feishu-base/connection/",
        FeishuBaseConnectionView.as_view(),
        name="feishu_base_connection",
    ),
    path(
        "feishu-base/connection/test/",
        FeishuBaseConnectionTestView.as_view(),
        name="feishu_base_connection_test",
    ),
    path(
        "linkedin/connection/",
        LinkedInConnectionView.as_view(),
        name="linkedin_connection",
    ),
    path(
        "apollo/connection/",
        ApolloConnectionView.as_view(),
        name="apollo_connection",
    ),
    path(
        "whatsapp/connection/",
        WhatsAppBusinessConnectionView.as_view(),
        name="whatsapp_connection",
    ),
    path(
        "whatsapp/webhook/",
        WhatsAppWebhookView.as_view(),
        name="whatsapp_webhook",
    ),
    path(
        "facebook/oauth/start/",
        FacebookOAuthStartView.as_view(),
        name="facebook_oauth_start",
    ),
    path(
        "facebook/oauth/callback/",
        FacebookOAuthCallbackView.as_view(),
        name="facebook_oauth_callback",
    ),
    path(
        "facebook/oauth/sessions/<uuid:session_id>/",
        FacebookOAuthSessionView.as_view(),
        name="facebook_oauth_session",
    ),
    path(
        "facebook/oauth/sessions/<uuid:session_id>/select/",
        FacebookOAuthPageSelectionView.as_view(),
        name="facebook_oauth_select_pages",
    ),
    path(
        "facebook/pages/",
        FacebookPageConnectionListCreateView.as_view(),
        name="facebook_pages",
    ),
    path(
        "facebook/pages/<uuid:connection_id>/",
        FacebookPageConnectionDetailView.as_view(),
        name="facebook_page_detail",
    ),
    path(
        "facebook/conversions/",
        FacebookConversionSettingsView.as_view(),
        name="facebook_conversion_settings",
    ),
    path(
        "facebook/conversations/leads/<uuid:lead_id>/",
        FacebookMessengerConversationView.as_view(),
        name="facebook_messenger_conversation",
    ),
    path(
        "facebook/webhook/",
        FacebookWebhookView.as_view(),
        name="facebook_webhook",
    ),
]
