from django.urls import path

from integrations.api.views import (
    ApolloConnectionTestView,
    ApolloConnectionView,
    ChannelSafetyApprovalCreateView,
    ChannelSafetyChannelView,
    ChannelSafetyOrganizationView,
    ChannelSafetySummaryView,
    ChannelSafetyTargetDetailView,
    ChannelSafetyTargetListCreateView,
    ChannelSafetyUnknownResolveView,
    FacebookConversionSettingsView,
    FacebookMessengerConversationView,
    FacebookOAuthCallbackView,
    FacebookOAuthPageSelectionView,
    FacebookOAuthSessionView,
    FacebookOAuthStartView,
    FacebookPageConnectionDetailView,
    FacebookPageConnectionListCreateView,
    FacebookWebhookView,
    FeishuBaseConnectionTestView,
    FeishuBaseConnectionView,
    FeishuBasePersonImportDetailView,
    FeishuBasePersonImportPreviewView,
    FeishuBaseRemoteDeleteView,
    FeishuBaseResearchSyncView,
    FeishuBaseSyncListView,
    LinkedInConnectionTestView,
    LinkedInConnectionView,
    WhatsAppBusinessConnectionTestView,
    WhatsAppBusinessConnectionView,
    WhatsAppMessageExecutionView,
    WhatsAppMessageListView,
    WhatsAppWebhookView,
)

app_name = "api_integrations"

urlpatterns = [
    path("channel-safety/", ChannelSafetySummaryView.as_view(), name="channel_safety"),
    path("channel-safety/organization/", ChannelSafetyOrganizationView.as_view(), name="channel_safety_organization"),
    path("channel-safety/channels/<str:channel>/", ChannelSafetyChannelView.as_view(), name="channel_safety_channel"),
    path("channel-safety/test-targets/", ChannelSafetyTargetListCreateView.as_view(), name="channel_safety_targets"),
    path("channel-safety/test-targets/<uuid:target_id>/", ChannelSafetyTargetDetailView.as_view(), name="channel_safety_target_detail"),
    path("channel-safety/approvals/", ChannelSafetyApprovalCreateView.as_view(), name="channel_safety_approvals"),
    path("channel-safety/unknown/<uuid:request_id>/resolve/", ChannelSafetyUnknownResolveView.as_view(), name="channel_safety_unknown_resolve"),
    path(
        "feishu-base/connection/",
        FeishuBaseConnectionView.as_view(),
        name="feishu_base_connection",
    ),
    path(
        "feishu-base/connection/test/",
        FeishuBaseConnectionTestView.as_view(),
        name="feishu_base_connection_test",
    ),
    path(
        "feishu-base/intakes/<uuid:intake_id>/sync/",
        FeishuBaseResearchSyncView.as_view(),
        name="feishu_base_research_sync",
    ),
    path(
        "feishu-base/syncs/",
        FeishuBaseSyncListView.as_view(),
        name="feishu_base_syncs",
    ),
    path(
        "feishu-base/syncs/<uuid:sync_id>/delete/",
        FeishuBaseRemoteDeleteView.as_view(),
        name="feishu_base_remote_delete",
    ),
    path(
        "feishu-base/person-imports/preview/",
        FeishuBasePersonImportPreviewView.as_view(),
        name="feishu_base_person_import_preview",
    ),
    path(
        "feishu-base/person-imports/<uuid:import_id>/",
        FeishuBasePersonImportDetailView.as_view(),
        name="feishu_base_person_import_detail",
    ),
    path(
        "linkedin/connection/",
        LinkedInConnectionView.as_view(),
        name="linkedin_connection",
    ),
    path(
        "linkedin/connection/test/",
        LinkedInConnectionTestView.as_view(),
        name="linkedin_connection_test",
    ),
    path(
        "apollo/connection/",
        ApolloConnectionView.as_view(),
        name="apollo_connection",
    ),
    path(
        "apollo/connection/test/",
        ApolloConnectionTestView.as_view(),
        name="apollo_connection_test",
    ),
    path(
        "whatsapp/connection/",
        WhatsAppBusinessConnectionView.as_view(),
        name="whatsapp_connection",
    ),
    path(
        "whatsapp/connection/test/",
        WhatsAppBusinessConnectionTestView.as_view(),
        name="whatsapp_connection_test",
    ),
    path(
        "whatsapp/messages/",
        WhatsAppMessageListView.as_view(),
        name="whatsapp_message_list",
    ),
    path(
        "whatsapp/messages/<uuid:message_id>/execution/",
        WhatsAppMessageExecutionView.as_view(),
        name="whatsapp_message_execution",
    ),
    path(
        "whatsapp/webhook/",
        WhatsAppWebhookView.as_view(),
        name="whatsapp_webhook",
    ),
    path(
        "facebook/oauth/start/",
        FacebookOAuthStartView.as_view(),
        name="facebook_oauth_start",
    ),
    path(
        "facebook/oauth/callback/",
        FacebookOAuthCallbackView.as_view(),
        name="facebook_oauth_callback",
    ),
    path(
        "facebook/oauth/sessions/<uuid:session_id>/",
        FacebookOAuthSessionView.as_view(),
        name="facebook_oauth_session",
    ),
    path(
        "facebook/oauth/sessions/<uuid:session_id>/select/",
        FacebookOAuthPageSelectionView.as_view(),
        name="facebook_oauth_select_pages",
    ),
    path(
        "facebook/pages/",
        FacebookPageConnectionListCreateView.as_view(),
        name="facebook_pages",
    ),
    path(
        "facebook/pages/<uuid:connection_id>/",
        FacebookPageConnectionDetailView.as_view(),
        name="facebook_page_detail",
    ),
    path(
        "facebook/conversions/",
        FacebookConversionSettingsView.as_view(),
        name="facebook_conversion_settings",
    ),
    path(
        "facebook/conversations/leads/<uuid:lead_id>/",
        FacebookMessengerConversationView.as_view(),
        name="facebook_messenger_conversation",
    ),
    path(
        "facebook/webhook/",
        FacebookWebhookView.as_view(),
        name="facebook_webhook",
    ),
]
