from django.urls import path

from sdr.api.views import (
    LeadInspectionDetailView,
    LeadInspectionListView,
    LeadIntakeDetailView,
    LeadIntakeListView,
    LeadNurtureEnrollmentActionView,
    LeadNurtureEnrollmentListView,
    SDRAnalyticsView,
    SDRComplianceDeletionActionView,
    SDRComplianceOverviewView,
    SDRComplianceRetentionScanView,
    SDRComplianceRuleDetailView,
    SDRComplianceRuleListCreateView,
    SDRComplianceSettingsView,
    SDRDataProvenanceDetailView,
    SDRDataProvenanceListView,
    SDRDoNotContactDetailView,
    SDRDoNotContactListCreateView,
    SDREmailSuppressionDetailView,
    SDREmailSuppressionListCreateView,
    SDRIntelligenceSettingsView,
    SDRNurtureSequenceDetailView,
    SDRNurtureSequenceListCreateView,
    SDROutboundCampaignActionView,
    SDROutboundCampaignAnalyticsView,
    SDROutboundCampaignDetailView,
    SDROutboundCampaignListCreateView,
    SDROutboundCopyDraftActionView,
    SDROutboundCopyDraftDetailView,
    SDROutboundCopyDraftListCreateView,
    SDROutboundProspectActionView,
    SDROutboundProspectImportView,
    SDROutboundProspectListView,
    SDROutboundSourceDetailView,
    SDROutboundSourceListCreateView,
    SDROutboundSourceSyncView,
    SDRResponseSettingsView,
    SDRRoutingPreviewView,
    SDRRoutingRuleDetailView,
    SDRRoutingRuleListCreateView,
    SDRSalesFeedbackLeadView,
)
from sdr.ses_views import SESFeedbackWebhookView
from sdr.tracking_views import NurtureClickTrackingView, NurtureOpenTrackingView
from sdr.unsubscribe_views import NurtureUnsubscribeView

app_name = "api_sdr"

urlpatterns = [
    path("analytics/funnel/", SDRAnalyticsView.as_view(), name="analytics_funnel"),
    path(
        "compliance/",
        SDRComplianceOverviewView.as_view(),
        name="compliance_overview",
    ),
    path(
        "compliance/settings/",
        SDRComplianceSettingsView.as_view(),
        name="compliance_settings",
    ),
    path(
        "compliance/rules/",
        SDRComplianceRuleListCreateView.as_view(),
        name="compliance_rule_list_create",
    ),
    path(
        "compliance/rules/<uuid:rule_id>/",
        SDRComplianceRuleDetailView.as_view(),
        name="compliance_rule_detail",
    ),
    path(
        "compliance/dnc/",
        SDRDoNotContactListCreateView.as_view(),
        name="compliance_dnc_list_create",
    ),
    path(
        "compliance/dnc/<uuid:entry_id>/",
        SDRDoNotContactDetailView.as_view(),
        name="compliance_dnc_detail",
    ),
    path(
        "compliance/provenance/",
        SDRDataProvenanceListView.as_view(),
        name="compliance_provenance_list",
    ),
    path(
        "compliance/provenance/<uuid:intake_id>/",
        SDRDataProvenanceDetailView.as_view(),
        name="compliance_provenance_detail",
    ),
    path(
        "compliance/intakes/<uuid:intake_id>/deletion/",
        SDRComplianceDeletionActionView.as_view(),
        name="compliance_deletion_action",
    ),
    path(
        "compliance/retention/scan/",
        SDRComplianceRetentionScanView.as_view(),
        name="compliance_retention_scan",
    ),
    path(
        "sales-feedback/leads/<uuid:lead_id>/",
        SDRSalesFeedbackLeadView.as_view(),
        name="sales_feedback_lead",
    ),
    path(
        "outbound/campaigns/",
        SDROutboundCampaignListCreateView.as_view(),
        name="outbound_campaign_list_create",
    ),
    path(
        "outbound/campaigns/<uuid:campaign_id>/",
        SDROutboundCampaignDetailView.as_view(),
        name="outbound_campaign_detail",
    ),
    path(
        "outbound/campaigns/<uuid:campaign_id>/action/",
        SDROutboundCampaignActionView.as_view(),
        name="outbound_campaign_action",
    ),
    path(
        "outbound/campaigns/<uuid:campaign_id>/analytics/",
        SDROutboundCampaignAnalyticsView.as_view(),
        name="outbound_campaign_analytics",
    ),
    path(
        "outbound/campaigns/<uuid:campaign_id>/prospects/",
        SDROutboundProspectListView.as_view(),
        name="outbound_prospect_list",
    ),
    path(
        "outbound/campaigns/<uuid:campaign_id>/prospects/import/",
        SDROutboundProspectImportView.as_view(),
        name="outbound_prospect_import",
    ),
    path(
        "outbound/campaigns/<uuid:campaign_id>/sources/",
        SDROutboundSourceListCreateView.as_view(),
        name="outbound_source_list_create",
    ),
    path(
        "outbound/campaigns/<uuid:campaign_id>/copy-drafts/",
        SDROutboundCopyDraftListCreateView.as_view(),
        name="outbound_copy_draft_list_create",
    ),
    path(
        "outbound/copy-drafts/<uuid:draft_id>/",
        SDROutboundCopyDraftDetailView.as_view(),
        name="outbound_copy_draft_detail",
    ),
    path(
        "outbound/copy-drafts/<uuid:draft_id>/action/",
        SDROutboundCopyDraftActionView.as_view(),
        name="outbound_copy_draft_action",
    ),
    path(
        "outbound/sources/<uuid:source_id>/",
        SDROutboundSourceDetailView.as_view(),
        name="outbound_source_detail",
    ),
    path(
        "outbound/sources/<uuid:source_id>/sync/",
        SDROutboundSourceSyncView.as_view(),
        name="outbound_source_sync",
    ),
    path(
        "outbound/prospects/<uuid:prospect_id>/action/",
        SDROutboundProspectActionView.as_view(),
        name="outbound_prospect_action",
    ),
    path(
        "public/ses-feedback/",
        SESFeedbackWebhookView.as_view(),
        name="ses_feedback",
    ),
    path(
        "public/nurture/open/<str:token>/pixel.gif",
        NurtureOpenTrackingView.as_view(),
        name="nurture_open_tracking",
    ),
    path(
        "public/nurture/click/<str:token>/",
        NurtureClickTrackingView.as_view(),
        name="nurture_click_tracking",
    ),
    path(
        "public/nurture/unsubscribe/<str:token>/",
        NurtureUnsubscribeView.as_view(),
        name="nurture_unsubscribe",
    ),
    path(
        "nurture/sequences/",
        SDRNurtureSequenceListCreateView.as_view(),
        name="nurture_sequence_list_create",
    ),
    path(
        "nurture/sequences/<uuid:sequence_id>/",
        SDRNurtureSequenceDetailView.as_view(),
        name="nurture_sequence_detail",
    ),
    path(
        "nurture/enrollments/",
        LeadNurtureEnrollmentListView.as_view(),
        name="nurture_enrollment_list",
    ),
    path(
        "nurture/enrollments/<uuid:enrollment_id>/action/",
        LeadNurtureEnrollmentActionView.as_view(),
        name="nurture_enrollment_action",
    ),
    path(
        "nurture/suppressions/",
        SDREmailSuppressionListCreateView.as_view(),
        name="nurture_suppression_list_create",
    ),
    path(
        "nurture/suppressions/<uuid:suppression_id>/",
        SDREmailSuppressionDetailView.as_view(),
        name="nurture_suppression_detail",
    ),
    path(
        "response-settings/",
        SDRResponseSettingsView.as_view(),
        name="response_settings",
    ),
    path("intakes/", LeadIntakeListView.as_view(), name="intake_list"),
    path(
        "intakes/<uuid:intake_id>/",
        LeadIntakeDetailView.as_view(),
        name="intake_detail",
    ),
    path(
        "intelligence/settings/",
        SDRIntelligenceSettingsView.as_view(),
        name="intelligence_settings",
    ),
    path(
        "intelligence/inspections/",
        LeadInspectionListView.as_view(),
        name="inspection_list",
    ),
    path(
        "intelligence/inspections/<uuid:inspection_id>/",
        LeadInspectionDetailView.as_view(),
        name="inspection_detail",
    ),
    path(
        "routing-rules/",
        SDRRoutingRuleListCreateView.as_view(),
        name="routing_rule_list_create",
    ),
    path(
        "routing-rules/preview/",
        SDRRoutingPreviewView.as_view(),
        name="routing_rule_preview",
    ),
    path(
        "routing-rules/<uuid:rule_id>/",
        SDRRoutingRuleDetailView.as_view(),
        name="routing_rule_detail",
    ),
]
