# Generated by Django 6.0.7 on 2026-07-29

import uuid

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

from common.rls import get_disable_policy_sql, get_enable_policy_sql

RLS_TABLES = ("automation_job", "automation_job_attempt")


def enable_automation_rls(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    with schema_editor.connection.cursor() as cursor:
        for table in RLS_TABLES:
            cursor.execute(get_enable_policy_sql(table))


def disable_automation_rls(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    with schema_editor.connection.cursor() as cursor:
        for table in reversed(RLS_TABLES):
            cursor.execute(get_disable_policy_sql(table))


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("common", "0029_delete_sessiontoken"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AutomationJob",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Last Modified At"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=160)),
                ("idempotency_key", models.CharField(max_length=255)),
                ("queue", models.CharField(default="default", max_length=80)),
                ("payload", models.JSONField(default=dict)),
                ("result", models.JSONField(default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("retry_scheduled", "Retry scheduled"),
                            ("succeeded", "Succeeded"),
                            ("dead_letter", "Dead letter"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=24,
                    ),
                ),
                ("attempt_count", models.PositiveIntegerField(default=0)),
                (
                    "max_attempts",
                    models.PositiveIntegerField(
                        default=3,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                ("replay_count", models.PositiveIntegerField(default=0)),
                ("scheduled_for", models.DateTimeField()),
                ("queued_at", models.DateTimeField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("last_error_code", models.CharField(blank=True, max_length=80)),
                ("last_error_message", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "org",
                    models.ForeignKey(
                        help_text="Organization this record belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="common.org",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Last Modified By",
                    ),
                ),
            ],
            options={
                "db_table": "automation_job",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="AutomationJobAttempt",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Last Modified At"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("attempt_number", models.PositiveIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "Running"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                        ],
                        default="running",
                        max_length=16,
                    ),
                ),
                ("started_at", models.DateTimeField()),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("error_code", models.CharField(blank=True, max_length=80)),
                ("error_message", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to="automation.automationjob",
                    ),
                ),
                (
                    "org",
                    models.ForeignKey(
                        help_text="Organization this record belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="common.org",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Last Modified By",
                    ),
                ),
            ],
            options={
                "db_table": "automation_job_attempt",
                "ordering": ("-attempt_number",),
            },
        ),
        migrations.AddIndex(
            model_name="automationjob",
            index=models.Index(
                fields=["org", "status", "scheduled_for"],
                name="automation__org_id_c6c8ab_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="automationjob",
            index=models.Index(
                fields=["org", "name", "-created_at"],
                name="automation__org_id_f12760_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="automationjob",
            constraint=models.UniqueConstraint(
                fields=("org", "name", "idempotency_key"),
                name="unique_automation_job_key_per_org",
            ),
        ),
        migrations.AddIndex(
            model_name="automationjobattempt",
            index=models.Index(
                fields=["org", "status", "-started_at"],
                name="automation__org_id_6535e2_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="automationjobattempt",
            constraint=models.UniqueConstraint(
                fields=("job", "attempt_number"),
                name="unique_automation_attempt_number",
            ),
        ),
        migrations.RunPython(enable_automation_rls, disable_automation_rls),
    ]
