# Generated by Django 6.0.7 on 2026-08-23 10:52

import uuid

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

import matching.models
from common.rls import get_disable_policy_sql, get_enable_policy_sql

RLS_TABLES = (
    "matching_person",
    "matching_person_identity",
    "matching_evidence",
    "matching_opportunity",
    "matching_match",
    "matching_match_evidence",
)


def enable_matching_rls(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    with schema_editor.connection.cursor() as cursor:
        for table in RLS_TABLES:
            cursor.execute(get_enable_policy_sql(table))


def disable_matching_rls(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    with schema_editor.connection.cursor() as cursor:
        for table in reversed(RLS_TABLES):
            cursor.execute(get_disable_policy_sql(table))


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("common", "0029_delete_sessiontoken"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MatchOpportunity",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Last Modified At"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "opportunity_type",
                    models.CharField(
                        choices=[
                            ("customer", "Customer"),
                            ("employment", "Employment"),
                            ("contractor", "Contractor"),
                            ("project", "Project"),
                            ("expert", "Expert"),
                            ("referral", "Referral"),
                            ("partnership", "Partnership"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("open", "Open"),
                            ("paused", "Paused"),
                            ("filled", "Filled"),
                            ("closed", "Closed"),
                        ],
                        default="draft",
                        max_length=16,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("organization_name", models.CharField(blank=True, max_length=255)),
                ("location", models.CharField(blank=True, max_length=255)),
                ("remote_mode", models.CharField(blank=True, max_length=40)),
                ("required_criteria", models.JSONField(default=dict)),
                ("preferred_criteria", models.JSONField(default=dict)),
                ("exclusion_criteria", models.JSONField(default=dict)),
                (
                    "scoring_weights",
                    models.JSONField(default=matching.models.default_scoring_weights),
                ),
                ("opened_at", models.DateTimeField(blank=True, null=True)),
                ("closes_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "org",
                    models.ForeignKey(
                        help_text="Organization this record belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="common.org",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="owned_match_opportunities",
                        to="common.profile",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Last Modified By",
                    ),
                ),
            ],
            options={
                "db_table": "matching_opportunity",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Last Modified At"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("display_name", models.CharField(max_length=255)),
                ("first_name", models.CharField(blank=True, max_length=120)),
                ("last_name", models.CharField(blank=True, max_length=120)),
                ("headline", models.CharField(blank=True, max_length=500)),
                ("summary", models.TextField(blank=True)),
                ("current_title", models.CharField(blank=True, max_length=255)),
                ("current_company", models.CharField(blank=True, max_length=255)),
                ("location", models.CharField(blank=True, max_length=255)),
                ("timezone", models.CharField(blank=True, max_length=64)),
                ("skills", models.JSONField(default=list)),
                ("roles", models.JSONField(default=list)),
                ("attributes", models.JSONField(default=dict)),
                (
                    "availability",
                    models.CharField(
                        choices=[
                            ("unknown", "Unknown"),
                            ("available", "Available"),
                            ("open_to_offers", "Open to offers"),
                            ("busy", "Busy"),
                            ("unavailable", "Unavailable"),
                        ],
                        default="unknown",
                        max_length=24,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("archived", "Archived"),
                        ],
                        default="active",
                        max_length=16,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "org",
                    models.ForeignKey(
                        help_text="Organization this record belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="common.org",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Last Modified By",
                    ),
                ),
            ],
            options={
                "db_table": "matching_person",
                "ordering": ("display_name", "id"),
            },
        ),
        migrations.CreateModel(
            name="Match",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Last Modified At"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("proposed", "Proposed"),
                            ("reviewing", "Reviewing"),
                            ("shortlisted", "Shortlisted"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                            ("expired", "Expired"),
                        ],
                        default="proposed",
                        max_length=24,
                    ),
                ),
                (
                    "overall_score",
                    models.PositiveSmallIntegerField(
                        default=0,
                        validators=[django.core.validators.MaxValueValidator(100)],
                    ),
                ),
                (
                    "eligibility_score",
                    models.PositiveSmallIntegerField(
                        default=0,
                        validators=[django.core.validators.MaxValueValidator(100)],
                    ),
                ),
                (
                    "fit_score",
                    models.PositiveSmallIntegerField(
                        default=0,
                        validators=[django.core.validators.MaxValueValidator(100)],
                    ),
                ),
                (
                    "trust_score",
                    models.PositiveSmallIntegerField(
                        default=0,
                        validators=[django.core.validators.MaxValueValidator(100)],
                    ),
                ),
                (
                    "relationship_score",
                    models.PositiveSmallIntegerField(
                        default=0,
                        validators=[django.core.validators.MaxValueValidator(100)],
                    ),
                ),
                (
                    "availability_score",
                    models.PositiveSmallIntegerField(
                        default=0,
                        validators=[django.core.validators.MaxValueValidator(100)],
                    ),
                ),
                (
                    "confidence",
                    models.DecimalField(
                        decimal_places=3,
                        default=0,
                        max_digits=4,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1),
                        ],
                    ),
                ),
                ("rank", models.PositiveIntegerField(blank=True, null=True)),
                ("reasons", models.JSONField(default=list)),
                ("gaps", models.JSONField(default=list)),
                ("score_breakdown", models.JSONField(default=dict)),
                ("engine_version", models.CharField(default="rules-v1", max_length=64)),
                ("model_provider", models.CharField(blank=True, max_length=40)),
                ("model_name", models.CharField(blank=True, max_length=120)),
                (
                    "evaluated_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "org",
                    models.ForeignKey(
                        help_text="Organization this record belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="common.org",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Last Modified By",
                    ),
                ),
                (
                    "opportunity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matches",
                        to="matching.matchopportunity",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matches",
                        to="matching.person",
                    ),
                ),
            ],
            options={
                "db_table": "matching_match",
                "ordering": ("rank", "-overall_score", "person__display_name"),
            },
        ),
        migrations.CreateModel(
            name="Evidence",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Last Modified At"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("profile", "Profile"),
                            ("skill", "Skill"),
                            ("experience", "Experience"),
                            ("relationship", "Relationship"),
                            ("interaction", "Interaction"),
                            ("availability", "Availability"),
                            ("preference", "Preference"),
                            ("verification", "Verification"),
                            ("other", "Other"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("crm", "CRM"),
                            ("apollo", "Apollo"),
                            ("linkedin", "LinkedIn"),
                            ("whatsapp", "WhatsApp"),
                            ("wechat", "WeChat"),
                            ("feishu", "Feishu"),
                            ("email", "Email"),
                            ("manual", "Manual"),
                            ("ai", "AI"),
                            ("other", "Other"),
                        ],
                        max_length=24,
                    ),
                ),
                ("summary", models.TextField()),
                ("facts", models.JSONField(default=dict)),
                ("source_uri", models.URLField(blank=True, max_length=1000)),
                ("source_record_id", models.CharField(blank=True, max_length=255)),
                (
                    "observed_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("valid_until", models.DateTimeField(blank=True, null=True)),
                (
                    "confidence",
                    models.DecimalField(
                        decimal_places=3,
                        default=0.5,
                        max_digits=4,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1),
                        ],
                    ),
                ),
                ("content_hash", models.CharField(editable=False, max_length=64)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "org",
                    models.ForeignKey(
                        help_text="Organization this record belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="common.org",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Last Modified By",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evidence",
                        to="matching.person",
                    ),
                ),
            ],
            options={
                "db_table": "matching_evidence",
                "ordering": ("-observed_at", "-created_at"),
            },
        ),
        migrations.CreateModel(
            name="PersonIdentity",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Last Modified At"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("email", "Email"),
                            ("phone", "Phone"),
                            ("linkedin", "LinkedIn"),
                            ("whatsapp", "WhatsApp"),
                            ("wechat", "WeChat"),
                            ("external", "External"),
                        ],
                        max_length=24,
                    ),
                ),
                ("normalized_value", models.CharField(max_length=500)),
                ("display_value", models.CharField(blank=True, max_length=500)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("crm", "CRM"),
                            ("apollo", "Apollo"),
                            ("linkedin", "LinkedIn"),
                            ("whatsapp", "WhatsApp"),
                            ("wechat", "WeChat"),
                            ("feishu", "Feishu"),
                            ("email", "Email"),
                            ("manual", "Manual"),
                            ("ai", "AI"),
                            ("other", "Other"),
                        ],
                        default="manual",
                        max_length=24,
                    ),
                ),
                ("is_primary", models.BooleanField(default=False)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "org",
                    models.ForeignKey(
                        help_text="Organization this record belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="common.org",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="identities",
                        to="matching.person",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Last Modified By",
                    ),
                ),
            ],
            options={
                "db_table": "matching_person_identity",
                "ordering": ("kind", "normalized_value"),
            },
        ),
        migrations.CreateModel(
            name="MatchEvidence",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Last Modified At"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[
                            ("positive", "Positive"),
                            ("negative", "Negative"),
                            ("neutral", "Neutral"),
                        ],
                        default="positive",
                        max_length=16,
                    ),
                ),
                (
                    "relevance",
                    models.DecimalField(
                        decimal_places=3,
                        default=0,
                        max_digits=4,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1),
                        ],
                    ),
                ),
                (
                    "contribution",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=6,
                        validators=[
                            django.core.validators.MinValueValidator(-100),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("explanation", models.CharField(blank=True, max_length=500)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "evidence",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="match_links",
                        to="matching.evidence",
                    ),
                ),
                (
                    "match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evidence_links",
                        to="matching.match",
                    ),
                ),
                (
                    "org",
                    models.ForeignKey(
                        help_text="Organization this record belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="common.org",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Last Modified By",
                    ),
                ),
            ],
            options={
                "db_table": "matching_match_evidence",
                "ordering": ("-relevance", "-contribution"),
                "indexes": [
                    models.Index(
                        fields=["org", "match", "-relevance"],
                        name="matching_ma_org_id_47051e_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("match", "evidence"), name="unique_evidence_per_match"
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="matchopportunity",
            index=models.Index(
                fields=["org", "status", "opportunity_type", "-created_at"],
                name="matching_op_org_id_22355f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="matchopportunity",
            index=models.Index(
                fields=["org", "owner", "status"], name="matching_op_org_id_bf16c1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="person",
            index=models.Index(
                fields=["org", "status", "display_name"],
                name="matching_pe_org_id_d8649a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="person",
            index=models.Index(
                fields=["org", "availability", "-updated_at"],
                name="matching_pe_org_id_d7a7bc_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="match",
            index=models.Index(
                fields=["org", "opportunity", "-overall_score"],
                name="matching_ma_org_id_a300e3_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="match",
            index=models.Index(
                fields=["org", "person", "status"], name="matching_ma_org_id_3676c4_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="match",
            constraint=models.UniqueConstraint(
                fields=("org", "person", "opportunity"),
                name="unique_person_opportunity_match",
            ),
        ),
        migrations.AddIndex(
            model_name="evidence",
            index=models.Index(
                fields=["org", "person", "kind", "-observed_at"],
                name="matching_ev_org_id_808fb1_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="evidence",
            index=models.Index(
                fields=["org", "source", "source_record_id"],
                name="matching_ev_org_id_6841eb_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="evidence",
            constraint=models.UniqueConstraint(
                condition=models.Q(("source_record_id", ""), _negated=True),
                fields=("org", "person", "source", "source_record_id"),
                name="unique_matching_source_record",
            ),
        ),
        migrations.AddIndex(
            model_name="personidentity",
            index=models.Index(
                fields=["org", "person", "kind"], name="matching_pe_org_id_ad8e81_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="personidentity",
            constraint=models.UniqueConstraint(
                fields=("org", "kind", "normalized_value"),
                name="unique_matching_identity_per_org",
            ),
        ),
        migrations.RunPython(enable_matching_rls, disable_matching_rls),
    ]
