# Generated by Django 6.0.7 on 2026-08-25 08:45

import uuid

import django.db.models.deletion
import django.db.models.expressions
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

from common.rls import get_disable_policy_sql, get_enable_policy_sql

RLS_TABLES = (
    "matching_match_run",
    "matching_match_revision",
    "matching_match_decision_event",
)


def enable_matching_history_rls(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    with schema_editor.connection.cursor() as cursor:
        for table in RLS_TABLES:
            cursor.execute(get_enable_policy_sql(table))


def disable_matching_history_rls(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    with schema_editor.connection.cursor() as cursor:
        for table in reversed(RLS_TABLES):
            cursor.execute(get_disable_policy_sql(table))


CREATE_POSTGRES_GUARDS_SQL = """
CREATE OR REPLACE FUNCTION matching_reject_history_mutation()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    RAISE EXCEPTION 'matching history is append-only'
        USING ERRCODE = '55000';
END;
$$;

CREATE TRIGGER matching_revision_append_only
BEFORE UPDATE OR DELETE ON matching_match_revision
FOR EACH ROW EXECUTE FUNCTION matching_reject_history_mutation();

CREATE TRIGGER matching_decision_event_append_only
BEFORE UPDATE OR DELETE ON matching_match_decision_event
FOR EACH ROW EXECUTE FUNCTION matching_reject_history_mutation();

CREATE OR REPLACE FUNCTION matching_validate_history_org()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    IF TG_TABLE_NAME = 'matching_match_run' THEN
        IF NOT EXISTS (
            SELECT 1 FROM matching_opportunity
            WHERE id = NEW.opportunity_id AND org_id = NEW.org_id
        ) THEN
            RAISE EXCEPTION 'match run opportunity belongs to another org'
                USING ERRCODE = '23514';
        END IF;
        IF NEW.automation_job_id IS NOT NULL AND NOT EXISTS (
            SELECT 1 FROM automation_job
            WHERE id = NEW.automation_job_id AND org_id = NEW.org_id
        ) THEN
            RAISE EXCEPTION 'match run automation job belongs to another org'
                USING ERRCODE = '23514';
        END IF;
        IF NEW.requested_by_id IS NOT NULL AND NOT EXISTS (
            SELECT 1 FROM profile
            WHERE id = NEW.requested_by_id AND org_id = NEW.org_id
        ) THEN
            RAISE EXCEPTION 'match run requester belongs to another org'
                USING ERRCODE = '23514';
        END IF;
    ELSIF TG_TABLE_NAME = 'matching_match_revision' THEN
        IF NOT EXISTS (
            SELECT 1
            FROM matching_match m
            JOIN matching_match_run r
              ON r.id = NEW.run_id
             AND r.org_id = NEW.org_id
             AND r.opportunity_id = m.opportunity_id
             AND r.ranking_revision = NEW.revision
            WHERE m.id = NEW.match_id
              AND m.org_id = NEW.org_id
              AND m.ranking_revision = NEW.revision
        ) THEN
            RAISE EXCEPTION 'match revision does not match current ranking projection'
                USING ERRCODE = '23514';
        END IF;
    ELSIF TG_TABLE_NAME = 'matching_match_decision_event' THEN
        IF btrim(NEW.reason_code) = '' THEN
            RAISE EXCEPTION 'match decision reason code is required'
                USING ERRCODE = '23514';
        END IF;
        IF NOT EXISTS (
            SELECT 1 FROM matching_match
            WHERE id = NEW.match_id
              AND org_id = NEW.org_id
              AND status = NEW.to_status
              AND decision_revision = NEW.resulting_decision_revision
              AND ranking_revision = NEW.based_on_ranking_revision
        ) THEN
            RAISE EXCEPTION 'match decision does not match current projection'
                USING ERRCODE = '23514';
        END IF;
        IF NEW.actor_id IS NOT NULL AND NOT EXISTS (
            SELECT 1 FROM profile
            WHERE id = NEW.actor_id AND org_id = NEW.org_id
        ) THEN
            RAISE EXCEPTION 'match decision actor belongs to another org'
                USING ERRCODE = '23514';
        END IF;
    END IF;
    RETURN NEW;
END;
$$;

CREATE TRIGGER matching_run_org_guard
BEFORE INSERT OR UPDATE ON matching_match_run
FOR EACH ROW EXECUTE FUNCTION matching_validate_history_org();

CREATE TRIGGER matching_revision_org_guard
BEFORE INSERT ON matching_match_revision
FOR EACH ROW EXECUTE FUNCTION matching_validate_history_org();

CREATE TRIGGER matching_decision_event_org_guard
BEFORE INSERT ON matching_match_decision_event
FOR EACH ROW EXECUTE FUNCTION matching_validate_history_org();
"""


DROP_POSTGRES_GUARDS_SQL = """
DROP TRIGGER IF EXISTS matching_decision_event_org_guard
    ON matching_match_decision_event;
DROP TRIGGER IF EXISTS matching_revision_org_guard ON matching_match_revision;
DROP TRIGGER IF EXISTS matching_run_org_guard ON matching_match_run;
DROP TRIGGER IF EXISTS matching_decision_event_append_only
    ON matching_match_decision_event;
DROP TRIGGER IF EXISTS matching_revision_append_only ON matching_match_revision;
DROP FUNCTION IF EXISTS matching_validate_history_org();
DROP FUNCTION IF EXISTS matching_reject_history_mutation();
"""


def create_postgres_guards(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(CREATE_POSTGRES_GUARDS_SQL)


def drop_postgres_guards(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(DROP_POSTGRES_GUARDS_SQL)


class Migration(migrations.Migration):

    dependencies = [
        ("automation", "0001_initial"),
        ("common", "0029_delete_sessiontoken"),
        ("matching", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="decided_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="match",
            name="decided_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="decided_matches",
                to="common.profile",
            ),
        ),
        migrations.AddField(
            model_name="match",
            name="decision_reason",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="match",
            name="decision_revision",
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="match",
            name="ranking_revision",
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="matchopportunity",
            name="ranking_revision",
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.CreateModel(
            name="MatchRun",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Last Modified At"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("request_hash", models.CharField(max_length=64)),
                ("requested_person_ids", models.JSONField(default=list)),
                ("total_count", models.PositiveIntegerField(default=0)),
                ("processed_count", models.PositiveIntegerField(default=0)),
                ("result_count", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "ranking_revision",
                    models.PositiveBigIntegerField(blank=True, null=True),
                ),
                ("engine_version", models.CharField(default="rules-v1", max_length=64)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "outcome",
                    models.CharField(
                        blank=True,
                        choices=[("succeeded", "Succeeded"), ("skipped", "Skipped")],
                        default="",
                        max_length=16,
                    ),
                ),
                (
                    "automation_job",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="match_run",
                        to="automation.automationjob",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "opportunity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="match_runs",
                        to="matching.matchopportunity",
                    ),
                ),
                (
                    "org",
                    models.ForeignKey(
                        help_text="Organization this record belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="common.org",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="requested_match_runs",
                        to="common.profile",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Last Modified By",
                    ),
                ),
            ],
            options={
                "db_table": "matching_match_run",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="MatchRevision",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Last Modified At"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("revision", models.PositiveBigIntegerField()),
                (
                    "revision_kind",
                    models.CharField(
                        choices=[("evaluation", "Evaluation"), ("rerank", "Rerank")],
                        default="evaluation",
                        max_length=16,
                    ),
                ),
                ("snapshot", models.JSONField(default=dict)),
                ("evidence_snapshot", models.JSONField(default=list)),
                ("engine_version", models.CharField(default="rules-v1", max_length=64)),
                (
                    "evaluated_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="revisions",
                        to="matching.match",
                    ),
                ),
                (
                    "org",
                    models.ForeignKey(
                        help_text="Organization this record belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="common.org",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Last Modified By",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="revisions",
                        to="matching.matchrun",
                    ),
                ),
            ],
            options={
                "db_table": "matching_match_revision",
                "ordering": ("-revision",),
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name="MatchDecisionEvent",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Last Modified At"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "from_status",
                    models.CharField(
                        choices=[
                            ("proposed", "Proposed"),
                            ("reviewing", "Reviewing"),
                            ("shortlisted", "Shortlisted"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                            ("expired", "Expired"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "to_status",
                    models.CharField(
                        choices=[
                            ("proposed", "Proposed"),
                            ("reviewing", "Reviewing"),
                            ("shortlisted", "Shortlisted"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                            ("expired", "Expired"),
                        ],
                        max_length=24,
                    ),
                ),
                ("reason_code", models.CharField(max_length=64)),
                ("reason", models.TextField(blank=True)),
                ("expected_decision_revision", models.PositiveBigIntegerField()),
                ("resulting_decision_revision", models.PositiveBigIntegerField()),
                (
                    "based_on_ranking_revision",
                    models.PositiveBigIntegerField(default=0),
                ),
                ("idempotency_key", models.CharField(max_length=128)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="match_decision_events",
                        to="common.profile",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="decision_events",
                        to="matching.match",
                    ),
                ),
                (
                    "org",
                    models.ForeignKey(
                        help_text="Organization this record belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="common.org",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Last Modified By",
                    ),
                ),
            ],
            options={
                "db_table": "matching_match_decision_event",
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["org", "match", "-created_at"],
                        name="matching_ma_org_id_01a2b4_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("org", "match", "resulting_decision_revision"),
                        name="unique_matching_decision_revision",
                    ),
                    models.UniqueConstraint(
                        fields=("org", "idempotency_key"),
                        name="unique_matching_decision_idempotency",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "resulting_decision_revision",
                                django.db.models.expressions.CombinedExpression(
                                    models.F("expected_decision_revision"),
                                    "+",
                                    models.Value(1),
                                ),
                            )
                        ),
                        name="matching_decision_revision_increments",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("from_status", models.F("to_status")), _negated=True
                        ),
                        name="matching_decision_changes_status",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("reason_code", ""), _negated=True),
                        name="matching_decision_reason_code_present",
                    ),
                ],
            },
            bases=(models.Model,),
        ),
        migrations.AddIndex(
            model_name="matchrun",
            index=models.Index(
                fields=["org", "opportunity", "-created_at"],
                name="matching_ma_org_id_eb7cba_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="matchrun",
            index=models.Index(
                fields=["org", "outcome", "-created_at"],
                name="matching_ma_org_id_981229_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="matchrun",
            index=models.Index(
                fields=["org", "request_hash"], name="matching_ma_org_id_4f5078_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="matchrevision",
            index=models.Index(
                fields=["org", "run", "revision"], name="matching_ma_org_id_549139_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="matchrevision",
            index=models.Index(
                fields=["org", "match", "-revision"],
                name="matching_ma_org_id_c0ff47_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="matchrevision",
            constraint=models.UniqueConstraint(
                fields=("match", "run"), name="unique_matching_revision_per_run"
            ),
        ),
        migrations.AddConstraint(
            model_name="matchrevision",
            constraint=models.UniqueConstraint(
                fields=("match", "revision"), name="unique_matching_revision_number"
            ),
        ),
        migrations.RunPython(
            enable_matching_history_rls,
            disable_matching_history_rls,
        ),
        migrations.RunPython(
            create_postgres_guards,
            drop_postgres_guards,
        ),
    ]
