# Generated by Django 6.0.7 on 2026-08-26 05:59

import hashlib
import uuid

import django.core.validators
import django.db.models.deletion
import django.db.models.expressions
import django.utils.timezone
import matching.models
from django.conf import settings
from django.db import migrations, models

from common.rls import get_disable_policy_sql, get_enable_policy_sql


RLS_TABLES = (
    "matching_evidence_provenance",
    "matching_evidence_governance_event",
    "matching_person_contact_intent",
    "matching_person_contact_intent_event",
)


def backfill_evidence_governance(apps, schema_editor):
    Evidence = apps.get_model("matching", "Evidence")
    Provenance = apps.get_model("matching", "EvidenceProvenance")
    Event = apps.get_model("matching", "EvidenceGovernanceEvent")
    postgres = schema_editor.connection.vendor == "postgresql"
    if postgres:
        with schema_editor.connection.cursor() as cursor:
            cursor.execute(
                'ALTER TABLE "matching_evidence" NO FORCE ROW LEVEL SECURITY'
            )
    try:
        for evidence in Evidence.objects.all().iterator(chunk_size=500):
            is_ai = evidence.source == "ai"
            confirmed_at = None if is_ai else evidence.created_at
            provenance = Provenance.objects.create(
                org_id=evidence.org_id,
                evidence_id=evidence.id,
                collection_method="ai_extraction" if is_ai else "other",
                lawful_basis="unassessed",
                allowed_channels=[
                    "email",
                    "whatsapp",
                    "linkedin",
                    "phone",
                    "wechat",
                ],
                allowed_purposes=[
                    "general_contact",
                    "customer",
                    "employment",
                    "contractor",
                    "project",
                    "expert",
                    "referral",
                    "partnership",
                ],
                confirmation_status="pending" if is_ai else "confirmed",
                confirmed_at=confirmed_at,
                revision=1,
            )
            request_hash = hashlib.sha256(
                f"matching-governance-backfill:{evidence.id}".encode("utf-8")
            ).hexdigest()
            Event.objects.create(
                org_id=evidence.org_id,
                provenance_id=provenance.id,
                evidence_id=evidence.id,
                action="created",
                expected_revision=0,
                resulting_revision=1,
                idempotency_key=uuid.uuid5(
                    uuid.NAMESPACE_URL,
                    f"matching:evidence-governance:{evidence.id}",
                ),
                request_hash=request_hash,
                safe_snapshot={
                    "confirmation_status": provenance.confirmation_status,
                    "processing_status": "active",
                    "lawful_basis": "unassessed",
                },
            )
    finally:
        if postgres:
            with schema_editor.connection.cursor() as cursor:
                cursor.execute(
                    'ALTER TABLE "matching_evidence" FORCE ROW LEVEL SECURITY'
                )


def enable_governance_rls(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    with schema_editor.connection.cursor() as cursor:
        for table in RLS_TABLES:
            cursor.execute(get_enable_policy_sql(table))


def disable_governance_rls(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    with schema_editor.connection.cursor() as cursor:
        for table in reversed(RLS_TABLES):
            cursor.execute(get_disable_policy_sql(table))


CREATE_GOVERNANCE_GUARDS_SQL = r"""
CREATE OR REPLACE FUNCTION matching_validate_governance_org()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    IF TG_TABLE_NAME = 'matching_evidence_provenance' THEN
        IF NOT EXISTS (
            SELECT 1 FROM matching_evidence
            WHERE id = NEW.evidence_id AND org_id = NEW.org_id
        ) THEN
            RAISE EXCEPTION 'matching governance child organization mismatch'
                USING ERRCODE = '23514';
        END IF;
        IF NEW.confirmed_by_id IS NOT NULL AND NOT EXISTS (
            SELECT 1 FROM profile
            WHERE id = NEW.confirmed_by_id AND org_id = NEW.org_id
        ) THEN
            RAISE EXCEPTION 'matching governance child organization mismatch'
                USING ERRCODE = '23514';
        END IF;
        IF NEW.confirmation_status = 'confirmed'
           AND EXISTS (
               SELECT 1 FROM matching_evidence
               WHERE id = NEW.evidence_id AND source = 'ai'
           )
           AND NEW.confirmed_by_id IS NULL THEN
            RAISE EXCEPTION 'AI evidence requires human confirmation'
                USING ERRCODE = '23514';
        END IF;
    ELSIF TG_TABLE_NAME = 'matching_evidence_governance_event' THEN
        IF NOT EXISTS (
            SELECT 1
            FROM matching_evidence_provenance p
            JOIN matching_evidence e
              ON e.id = NEW.evidence_id
             AND e.org_id = NEW.org_id
            WHERE p.id = NEW.provenance_id
              AND p.org_id = NEW.org_id
              AND p.evidence_id = e.id
              AND p.revision = NEW.resulting_revision
        ) THEN
            RAISE EXCEPTION 'matching governance event projection mismatch'
                USING ERRCODE = '23514';
        END IF;
        IF NEW.actor_id IS NOT NULL AND NOT EXISTS (
            SELECT 1 FROM profile
            WHERE id = NEW.actor_id AND org_id = NEW.org_id
        ) THEN
            RAISE EXCEPTION 'matching governance child organization mismatch'
                USING ERRCODE = '23514';
        END IF;
    ELSIF TG_TABLE_NAME = 'matching_person_contact_intent' THEN
        IF NOT EXISTS (
            SELECT 1 FROM matching_person
            WHERE id = NEW.person_id AND org_id = NEW.org_id
        ) THEN
            RAISE EXCEPTION 'matching governance child organization mismatch'
                USING ERRCODE = '23514';
        END IF;
        IF NEW.identity_id IS NOT NULL AND NOT EXISTS (
            SELECT 1 FROM matching_person_identity
            WHERE id = NEW.identity_id
              AND org_id = NEW.org_id
              AND person_id = NEW.person_id
        ) THEN
            RAISE EXCEPTION 'matching governance intent identity mismatch'
                USING ERRCODE = '23514';
        END IF;
        IF NEW.opportunity_id IS NOT NULL AND NOT EXISTS (
            SELECT 1 FROM matching_opportunity
            WHERE id = NEW.opportunity_id AND org_id = NEW.org_id
        ) THEN
            RAISE EXCEPTION 'matching governance child organization mismatch'
                USING ERRCODE = '23514';
        END IF;
        IF NEW.evidence_id IS NOT NULL AND NOT EXISTS (
            SELECT 1 FROM matching_evidence
            WHERE id = NEW.evidence_id
              AND org_id = NEW.org_id
              AND person_id = NEW.person_id
        ) THEN
            RAISE EXCEPTION 'matching governance intent evidence mismatch'
                USING ERRCODE = '23514';
        END IF;
    ELSIF TG_TABLE_NAME = 'matching_person_contact_intent_event' THEN
        IF NOT EXISTS (
            SELECT 1 FROM matching_person_contact_intent
            WHERE id = NEW.intent_id AND org_id = NEW.org_id
        ) THEN
            RAISE EXCEPTION 'matching governance child organization mismatch'
                USING ERRCODE = '23514';
        END IF;
        IF NEW.evidence_id IS NOT NULL AND NOT EXISTS (
            SELECT 1
            FROM matching_evidence e
            JOIN matching_person_contact_intent i
              ON i.id = NEW.intent_id
             AND i.org_id = NEW.org_id
             AND i.person_id = e.person_id
            WHERE e.id = NEW.evidence_id AND e.org_id = NEW.org_id
        ) THEN
            RAISE EXCEPTION 'matching governance intent evidence mismatch'
                USING ERRCODE = '23514';
        END IF;
        IF NEW.actor_id IS NOT NULL AND NOT EXISTS (
            SELECT 1 FROM profile
            WHERE id = NEW.actor_id AND org_id = NEW.org_id
        ) THEN
            RAISE EXCEPTION 'matching governance child organization mismatch'
                USING ERRCODE = '23514';
        END IF;
        IF NEW.source = 'ai' THEN
            IF NEW.confirmation_status <> 'pending'
               OR NEW.resulting_revision <> NEW.expected_revision THEN
                RAISE EXCEPTION 'AI contact intent must remain pending'
                    USING ERRCODE = '23514';
            END IF;
        ELSIF NOT EXISTS (
            SELECT 1 FROM matching_person_contact_intent
            WHERE id = NEW.intent_id
              AND org_id = NEW.org_id
              AND revision = NEW.resulting_revision
              AND state = NEW.to_state
        ) THEN
            RAISE EXCEPTION 'matching contact intent event projection mismatch'
                USING ERRCODE = '23514';
        END IF;
    END IF;
    RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION matching_reject_governance_event_mutation()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    RAISE EXCEPTION 'matching governance history is append-only'
        USING ERRCODE = '55000';
END;
$$;

CREATE TRIGGER matching_evidence_provenance_org_guard
BEFORE INSERT OR UPDATE ON matching_evidence_provenance
FOR EACH ROW EXECUTE FUNCTION matching_validate_governance_org();
CREATE TRIGGER matching_evidence_governance_event_org_guard
BEFORE INSERT ON matching_evidence_governance_event
FOR EACH ROW EXECUTE FUNCTION matching_validate_governance_org();
CREATE TRIGGER matching_contact_intent_org_guard
BEFORE INSERT OR UPDATE ON matching_person_contact_intent
FOR EACH ROW EXECUTE FUNCTION matching_validate_governance_org();
CREATE TRIGGER matching_contact_intent_event_org_guard
BEFORE INSERT ON matching_person_contact_intent_event
FOR EACH ROW EXECUTE FUNCTION matching_validate_governance_org();
CREATE TRIGGER matching_evidence_governance_event_append_only
BEFORE UPDATE OR DELETE ON matching_evidence_governance_event
FOR EACH ROW EXECUTE FUNCTION matching_reject_governance_event_mutation();
CREATE TRIGGER matching_contact_intent_event_append_only
BEFORE UPDATE OR DELETE ON matching_person_contact_intent_event
FOR EACH ROW EXECUTE FUNCTION matching_reject_governance_event_mutation();
"""


DROP_GOVERNANCE_GUARDS_SQL = r"""
DROP TRIGGER IF EXISTS matching_contact_intent_event_append_only
    ON matching_person_contact_intent_event;
DROP TRIGGER IF EXISTS matching_evidence_governance_event_append_only
    ON matching_evidence_governance_event;
DROP TRIGGER IF EXISTS matching_contact_intent_event_org_guard
    ON matching_person_contact_intent_event;
DROP TRIGGER IF EXISTS matching_contact_intent_org_guard
    ON matching_person_contact_intent;
DROP TRIGGER IF EXISTS matching_evidence_governance_event_org_guard
    ON matching_evidence_governance_event;
DROP TRIGGER IF EXISTS matching_evidence_provenance_org_guard
    ON matching_evidence_provenance;
DROP FUNCTION IF EXISTS matching_reject_governance_event_mutation();
DROP FUNCTION IF EXISTS matching_validate_governance_org();
"""


def create_governance_guards(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(CREATE_GOVERNANCE_GUARDS_SQL)


def drop_governance_guards(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(DROP_GOVERNANCE_GUARDS_SQL)


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0004_person_import_pipeline'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='anonymized_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='deletion_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='governance_revision',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='person',
            name='governance_status',
            field=models.CharField(choices=[('active', 'Active'), ('deletion_requested', 'Deletion requested'), ('anonymized', 'Anonymized')], default='active', max_length=24),
        ),
        migrations.AddField(
            model_name='person',
            name='retention_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='EvidenceProvenance',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('collection_method', models.CharField(choices=[('inbound_form', 'Inbound form'), ('direct_message', 'Direct message'), ('inbound_email', 'Inbound email'), ('provider_api', 'Provider API'), ('csv_import', 'CSV import'), ('manual', 'Manual entry'), ('ai_extraction', 'AI extraction'), ('other', 'Other')], default='other', max_length=24)),
                ('lawful_basis', models.CharField(choices=[('unassessed', 'Not assessed'), ('consent', 'Consent'), ('legitimate_interest', 'Legitimate interest'), ('contract', 'Contract / pre-contract request'), ('legal_obligation', 'Legal obligation'), ('public_task', 'Public task'), ('vital_interest', 'Vital interest')], default='unassessed', max_length=32)),
                ('lawful_basis_notes', models.TextField(blank=True)),
                ('consent_at', models.DateTimeField(blank=True, null=True)),
                ('consent_evidence_ref', models.CharField(blank=True, max_length=1000)),
                ('country_code', models.CharField(blank=True, max_length=3)),
                ('allowed_channels', models.JSONField(default=matching.models.default_governance_channels)),
                ('allowed_purposes', models.JSONField(default=matching.models.default_governance_purposes)),
                ('retention_until', models.DateTimeField(blank=True, null=True)),
                ('processing_status', models.CharField(choices=[('active', 'Active'), ('restricted', 'Restricted'), ('deletion_requested', 'Deletion requested'), ('anonymized', 'Anonymized')], default='active', max_length=24)),
                ('confirmation_status', models.CharField(choices=[('pending', 'Pending confirmation'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected')], default='confirmed', max_length=24)),
                ('source_content_sha256', models.CharField(blank=True, max_length=64)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('revision', models.PositiveBigIntegerField(default=0)),
                ('expiry_processed_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_matching_evidence', to='common.profile')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('evidence', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='provenance', to='matching.evidence')),
                ('org', models.ForeignKey(help_text='Organization this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='common.org')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
            ],
            options={
                'db_table': 'matching_evidence_provenance',
            },
        ),
        migrations.CreateModel(
            name='EvidenceGovernanceEvent',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('action', models.CharField(choices=[('created', 'Created'), ('provenance_updated', 'Provenance updated'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected'), ('expired', 'Expired'), ('restricted', 'Restricted'), ('deletion_requested', 'Deletion requested'), ('anonymized', 'Anonymized')], max_length=32)),
                ('expected_revision', models.PositiveBigIntegerField()),
                ('resulting_revision', models.PositiveBigIntegerField()),
                ('idempotency_key', models.UUIDField()),
                ('request_hash', models.CharField(max_length=64)),
                ('reason_code', models.CharField(blank=True, max_length=64)),
                ('safe_snapshot', models.JSONField(default=dict)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='evidence_governance_events', to='common.profile')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('evidence', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='governance_events', to='matching.evidence')),
                ('org', models.ForeignKey(help_text='Organization this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='common.org')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('provenance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='matching.evidenceprovenance')),
            ],
            options={
                'db_table': 'matching_evidence_governance_event',
                'ordering': ('-created_at',),
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='PersonContactIntent',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('whatsapp', 'WhatsApp'), ('linkedin', 'LinkedIn'), ('phone', 'Phone'), ('wechat', 'WeChat'), ('other', 'Other')], max_length=16)),
                ('purpose', models.CharField(choices=[('general_contact', 'General contact'), ('customer', 'Customer'), ('employment', 'Employment'), ('contractor', 'Contractor'), ('project', 'Project'), ('expert', 'Expert'), ('referral', 'Referral'), ('partnership', 'Partnership')], default='general_contact', max_length=24)),
                ('state', models.CharField(choices=[('unknown', 'Unknown'), ('open', 'Open'), ('conditional', 'Conditional'), ('not_open', 'Not open'), ('withdrawn', 'Withdrawn'), ('objected', 'Objected')], default='unknown', max_length=16)),
                ('source', models.CharField(choices=[('crm', 'CRM'), ('apollo', 'Apollo'), ('linkedin', 'LinkedIn'), ('whatsapp', 'WhatsApp'), ('wechat', 'WeChat'), ('feishu', 'Feishu'), ('email', 'Email'), ('manual', 'Manual'), ('ai', 'AI'), ('other', 'Other')], default='manual', max_length=24)),
                ('confidence', models.DecimalField(decimal_places=3, default=0.5, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('observed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('revision', models.PositiveBigIntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('evidence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_intents', to='matching.evidence')),
                ('identity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_intents', to='matching.personidentity')),
                ('opportunity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_intents', to='matching.matchopportunity')),
                ('org', models.ForeignKey(help_text='Organization this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='common.org')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_intents', to='matching.person')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
            ],
            options={
                'db_table': 'matching_person_contact_intent',
            },
        ),
        migrations.CreateModel(
            name='PersonContactIntentEvent',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('from_state', models.CharField(choices=[('unknown', 'Unknown'), ('open', 'Open'), ('conditional', 'Conditional'), ('not_open', 'Not open'), ('withdrawn', 'Withdrawn'), ('objected', 'Objected')], max_length=16)),
                ('to_state', models.CharField(choices=[('unknown', 'Unknown'), ('open', 'Open'), ('conditional', 'Conditional'), ('not_open', 'Not open'), ('withdrawn', 'Withdrawn'), ('objected', 'Objected')], max_length=16)),
                ('source', models.CharField(choices=[('crm', 'CRM'), ('apollo', 'Apollo'), ('linkedin', 'LinkedIn'), ('whatsapp', 'WhatsApp'), ('wechat', 'WeChat'), ('feishu', 'Feishu'), ('email', 'Email'), ('manual', 'Manual'), ('ai', 'AI'), ('other', 'Other')], max_length=24)),
                ('confirmation_status', models.CharField(choices=[('pending', 'Pending confirmation'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected')], max_length=24)),
                ('expected_revision', models.PositiveBigIntegerField()),
                ('resulting_revision', models.PositiveBigIntegerField()),
                ('idempotency_key', models.UUIDField()),
                ('request_hash', models.CharField(max_length=64)),
                ('reason_code', models.CharField(blank=True, max_length=64)),
                ('safe_snapshot', models.JSONField(default=dict)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contact_intent_events', to='common.profile')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('evidence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contact_intent_events', to='matching.evidence')),
                ('intent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='matching.personcontactintent')),
                ('org', models.ForeignKey(help_text='Organization this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='common.org')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
            ],
            options={
                'db_table': 'matching_person_contact_intent_event',
                'ordering': ('-created_at',),
            },
            bases=(models.Model,),
        ),
        migrations.RunPython(
            backfill_evidence_governance,
            migrations.RunPython.noop,
        ),
        migrations.AddIndex(
            model_name='evidenceprovenance',
            index=models.Index(fields=['org', 'processing_status', 'confirmation_status'], name='matching_ev_gov_status_idx'),
        ),
        migrations.AddIndex(
            model_name='evidenceprovenance',
            index=models.Index(fields=['org', 'retention_until', 'expiry_processed_at'], name='matching_ev_gov_expiry_idx'),
        ),
        migrations.AddConstraint(
            model_name='evidenceprovenance',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('lawful_basis', 'consent'), _negated=True), models.Q(('consent_at__isnull', False), models.Q(('consent_evidence_ref', ''), _negated=True)), _connector='OR'), name='matching_ev_gov_consent_complete'),
        ),
        migrations.AddConstraint(
            model_name='evidenceprovenance',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('confirmation_status', 'confirmed'), _negated=True), ('confirmed_at__isnull', False), _connector='OR'), name='matching_ev_gov_confirmation_time'),
        ),
        migrations.AddIndex(
            model_name='evidencegovernanceevent',
            index=models.Index(fields=['org', 'evidence', '-created_at'], name='matching_ev_org_id_e70f39_idx'),
        ),
        migrations.AddConstraint(
            model_name='evidencegovernanceevent',
            constraint=models.UniqueConstraint(fields=('org', 'idempotency_key'), name='unique_matching_ev_gov_event_key'),
        ),
        migrations.AddConstraint(
            model_name='evidencegovernanceevent',
            constraint=models.UniqueConstraint(fields=('org', 'provenance', 'resulting_revision'), name='unique_matching_ev_gov_revision'),
        ),
        migrations.AddConstraint(
            model_name='evidencegovernanceevent',
            constraint=models.CheckConstraint(condition=models.Q(('resulting_revision', django.db.models.expressions.CombinedExpression(models.F('expected_revision'), '+', models.Value(1)))), name='matching_ev_gov_revision_increments'),
        ),
        migrations.AddIndex(
            model_name='personcontactintent',
            index=models.Index(fields=['org', 'person', 'channel', 'purpose'], name='matching_pe_org_id_eb308e_idx'),
        ),
        migrations.AddIndex(
            model_name='personcontactintent',
            index=models.Index(fields=['org', 'state', 'valid_until'], name='matching_pe_org_id_a75409_idx'),
        ),
        migrations.AddConstraint(
            model_name='personcontactintent',
            constraint=models.UniqueConstraint(fields=('org', 'person', 'channel', 'purpose'), name='unique_matching_contact_intent'),
        ),
        migrations.AddIndex(
            model_name='personcontactintentevent',
            index=models.Index(fields=['org', 'intent', '-created_at'], name='matching_pe_org_id_c69149_idx'),
        ),
        migrations.AddConstraint(
            model_name='personcontactintentevent',
            constraint=models.UniqueConstraint(fields=('org', 'idempotency_key'), name='unique_matching_intent_event_key'),
        ),
        migrations.AddConstraint(
            model_name='person',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('governance_status', 'deletion_requested'), _negated=True), ('deletion_requested_at__isnull', False), _connector='OR'), name='matching_person_deletion_time'),
        ),
        migrations.AddConstraint(
            model_name='person',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('governance_status', 'anonymized'), _negated=True), ('anonymized_at__isnull', False), _connector='OR'), name='matching_person_anonymized_time'),
        ),
        migrations.AddConstraint(
            model_name='personcontactintent',
            constraint=models.CheckConstraint(condition=models.Q(('source', 'ai'), _negated=True), name='matching_intent_projection_not_ai'),
        ),
        migrations.AddConstraint(
            model_name='personcontactintent',
            constraint=models.CheckConstraint(condition=models.Q(('valid_until__isnull', True), ('valid_until__gte', models.F('observed_at')), _connector='OR'), name='matching_intent_validity_order'),
        ),
        migrations.AddConstraint(
            model_name='personcontactintentevent',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('confirmation_status', 'pending'), ('resulting_revision', models.F('expected_revision')), ('source', 'ai')), models.Q(models.Q(('source', 'ai'), _negated=True), ('confirmation_status', 'confirmed'), ('resulting_revision', django.db.models.expressions.CombinedExpression(models.F('expected_revision'), '+', models.Value(1)))), _connector='OR'), name='matching_intent_event_confirmation'),
        ),
        migrations.RunPython(enable_governance_rls, disable_governance_rls),
        migrations.RunPython(create_governance_guards, drop_governance_guards),
    ]
