# Generated by Django 6.0.7 on 2026-08-26 06:03

import django.db.models.deletion
import django.db.models.expressions
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models

from common.rls import get_disable_policy_sql, get_enable_policy_sql


CREATE_PERSON_GOVERNANCE_GUARDS_SQL = r"""
CREATE OR REPLACE FUNCTION matching_validate_person_governance_event()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM matching_person
        WHERE id = NEW.person_id
          AND org_id = NEW.org_id
          AND governance_revision = NEW.resulting_revision
    ) THEN
        RAISE EXCEPTION 'matching person governance event projection mismatch'
            USING ERRCODE = '23514';
    END IF;
    IF NEW.actor_id IS NOT NULL AND NOT EXISTS (
        SELECT 1 FROM profile
        WHERE id = NEW.actor_id AND org_id = NEW.org_id
    ) THEN
        RAISE EXCEPTION 'matching governance child organization mismatch'
            USING ERRCODE = '23514';
    END IF;
    RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION matching_reject_person_governance_event_mutation()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    RAISE EXCEPTION 'matching governance history is append-only'
        USING ERRCODE = '55000';
END;
$$;

CREATE TRIGGER matching_person_governance_event_org_guard
BEFORE INSERT ON matching_person_governance_event
FOR EACH ROW EXECUTE FUNCTION matching_validate_person_governance_event();
CREATE TRIGGER matching_person_governance_event_append_only
BEFORE UPDATE OR DELETE ON matching_person_governance_event
FOR EACH ROW EXECUTE FUNCTION matching_reject_person_governance_event_mutation();
"""


DROP_PERSON_GOVERNANCE_GUARDS_SQL = r"""
DROP TRIGGER IF EXISTS matching_person_governance_event_append_only
    ON matching_person_governance_event;
DROP TRIGGER IF EXISTS matching_person_governance_event_org_guard
    ON matching_person_governance_event;
DROP FUNCTION IF EXISTS matching_reject_person_governance_event_mutation();
DROP FUNCTION IF EXISTS matching_validate_person_governance_event();
"""


def enable_person_governance_security(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(get_enable_policy_sql("matching_person_governance_event"))
        cursor.execute(CREATE_PERSON_GOVERNANCE_GUARDS_SQL)


def disable_person_governance_security(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(DROP_PERSON_GOVERNANCE_GUARDS_SQL)
        cursor.execute(get_disable_policy_sql("matching_person_governance_event"))


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0005_person_anonymized_at_person_deletion_requested_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonGovernanceEvent',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('event_type', models.CharField(choices=[('deletion_requested', 'Deletion requested'), ('deletion_cancelled', 'Deletion cancelled'), ('anonymized', 'Anonymized'), ('export_requested', 'Export requested'), ('export_delivered', 'Export delivered'), ('export_invalidated', 'Export invalidated')], max_length=32)),
                ('idempotency_key', models.UUIDField()),
                ('request_hash', models.CharField(max_length=64)),
                ('expected_revision', models.PositiveBigIntegerField()),
                ('resulting_revision', models.PositiveBigIntegerField()),
                ('safe_snapshot', models.JSONField(default=dict)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='person_governance_events', to='common.profile')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('org', models.ForeignKey(help_text='Organization this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='common.org')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='governance_events', to='matching.person')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
            ],
            options={
                'db_table': 'matching_person_governance_event',
                'ordering': ('-occurred_at', '-created_at'),
                'indexes': [models.Index(fields=['org', 'person', '-occurred_at'], name='matching_pe_org_id_b37a79_idx')],
                'constraints': [models.UniqueConstraint(fields=('org', 'idempotency_key'), name='unique_matching_person_gov_event_key'), models.UniqueConstraint(fields=('org', 'person', 'resulting_revision', 'event_type'), name='unique_matching_person_gov_event_revision'), models.CheckConstraint(condition=models.Q(models.Q(('event_type__in', ['export_requested', 'export_delivered', 'export_invalidated']), ('resulting_revision', models.F('expected_revision'))), models.Q(('event_type__in', ['deletion_requested', 'deletion_cancelled', 'anonymized']), ('resulting_revision', django.db.models.expressions.CombinedExpression(models.F('expected_revision'), '+', models.Value(1)))), _connector='OR'), name='matching_person_gov_event_revision')],
            },
            bases=(models.Model,),
        ),
        migrations.RunPython(
            enable_person_governance_security,
            disable_person_governance_security,
        ),
    ]
