# Generated by Django 6.0.7 on 2026-08-26

import uuid

import django.db.models.deletion
import django.db.models.expressions
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

from common.rls import get_disable_policy_sql, get_enable_policy_sql


RLS_TABLES = (
    "matching_match_feedback_event",
    "matching_match_feedback_attribution",
)


CREATE_GUARDS_SQL = r"""
CREATE OR REPLACE FUNCTION matching_validate_feedback_child()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    IF TG_TABLE_NAME = 'matching_match_feedback_event' THEN
        IF NOT EXISTS (
            SELECT 1 FROM matching_match m
            WHERE m.id = NEW.match_id
              AND m.org_id = NEW.org_id
              AND m.feedback_revision = NEW.resulting_feedback_revision
              AND m.ranking_revision = NEW.based_on_ranking_revision
        ) THEN
            RAISE EXCEPTION 'matching feedback projection mismatch'
                USING ERRCODE = '23514';
        END IF;
        IF NEW.match_revision_id IS NOT NULL AND NOT EXISTS (
            SELECT 1 FROM matching_match_revision r
            WHERE r.id = NEW.match_revision_id
              AND r.org_id = NEW.org_id
              AND r.match_id = NEW.match_id
              AND r.revision = NEW.based_on_ranking_revision
        ) THEN
            RAISE EXCEPTION 'matching feedback child organization mismatch'
                USING ERRCODE = '23514';
        END IF;
        IF NEW.actor_id IS NOT NULL AND NOT EXISTS (
            SELECT 1 FROM profile p
            WHERE p.id = NEW.actor_id AND p.org_id = NEW.org_id
        ) THEN
            RAISE EXCEPTION 'matching feedback child organization mismatch'
                USING ERRCODE = '23514';
        END IF;
        IF NEW.supersedes_id IS NOT NULL AND NOT EXISTS (
            SELECT 1 FROM matching_match_feedback_event e
            WHERE e.id = NEW.supersedes_id
              AND e.org_id = NEW.org_id
              AND e.match_id = NEW.match_id
              AND e.event_kind = NEW.event_kind
        ) THEN
            RAISE EXCEPTION 'matching feedback child organization mismatch'
                USING ERRCODE = '23514';
        END IF;
    ELSIF TG_TABLE_NAME = 'matching_match_feedback_attribution' THEN
        IF NOT EXISTS (
            SELECT 1 FROM matching_match_feedback_event e
            WHERE e.id = NEW.feedback_event_id AND e.org_id = NEW.org_id
        ) THEN
            RAISE EXCEPTION 'matching feedback child organization mismatch'
                USING ERRCODE = '23514';
        END IF;
        IF NEW.evidence_id IS NOT NULL AND NOT EXISTS (
            SELECT 1
            FROM matching_match_feedback_event f
            JOIN matching_match m ON m.id = f.match_id AND m.org_id = NEW.org_id
            JOIN matching_evidence e ON e.id = NEW.evidence_id
              AND e.org_id = NEW.org_id AND e.person_id = m.person_id
            JOIN matching_match_revision r ON r.id = f.match_revision_id
              AND r.org_id = NEW.org_id AND r.match_id = m.id
            WHERE f.id = NEW.feedback_event_id
              AND f.org_id = NEW.org_id
              AND r.evidence_snapshot @> jsonb_build_array(
                  jsonb_build_object('evidence_id', NEW.evidence_id::text)
              )
        ) THEN
            RAISE EXCEPTION 'matching feedback evidence revision mismatch'
                USING ERRCODE = '23514';
        END IF;
    END IF;
    RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION matching_reject_feedback_mutation()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    RAISE EXCEPTION 'matching feedback history is append-only'
        USING ERRCODE = '55000';
END;
$$;

CREATE TRIGGER matching_feedback_event_child_guard
BEFORE INSERT ON matching_match_feedback_event
FOR EACH ROW EXECUTE FUNCTION matching_validate_feedback_child();
CREATE TRIGGER matching_feedback_attribution_child_guard
BEFORE INSERT ON matching_match_feedback_attribution
FOR EACH ROW EXECUTE FUNCTION matching_validate_feedback_child();
CREATE TRIGGER matching_feedback_event_append_only
BEFORE UPDATE OR DELETE ON matching_match_feedback_event
FOR EACH ROW EXECUTE FUNCTION matching_reject_feedback_mutation();
CREATE TRIGGER matching_feedback_attribution_append_only
BEFORE UPDATE OR DELETE ON matching_match_feedback_attribution
FOR EACH ROW EXECUTE FUNCTION matching_reject_feedback_mutation();
"""


DROP_GUARDS_SQL = r"""
DROP TRIGGER IF EXISTS matching_feedback_attribution_append_only
    ON matching_match_feedback_attribution;
DROP TRIGGER IF EXISTS matching_feedback_event_append_only
    ON matching_match_feedback_event;
DROP TRIGGER IF EXISTS matching_feedback_attribution_child_guard
    ON matching_match_feedback_attribution;
DROP TRIGGER IF EXISTS matching_feedback_event_child_guard
    ON matching_match_feedback_event;
DROP FUNCTION IF EXISTS matching_reject_feedback_mutation();
DROP FUNCTION IF EXISTS matching_validate_feedback_child();
"""


def enable_feedback_security(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    with schema_editor.connection.cursor() as cursor:
        for table in RLS_TABLES:
            cursor.execute(get_enable_policy_sql(table))
        cursor.execute(CREATE_GUARDS_SQL)


def disable_feedback_security(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(DROP_GUARDS_SQL)
        for table in reversed(RLS_TABLES):
            cursor.execute(get_disable_policy_sql(table))


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0030_profile_matching_access_level"),
        ("matching", "0006_person_governance_event"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="feedback_revision",
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="match",
            name="latest_outcome_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="match",
            name="latest_outcome_code",
            field=models.CharField(
                blank=True,
                choices=[
                    ("contact_attempted", "Contact attempted"),
                    ("contact_reached", "Contact reached"),
                    ("interview_scheduled", "Interview scheduled"),
                    ("interview_completed", "Interview completed"),
                    ("deal_won", "Deal won"),
                    ("deal_lost", "Deal lost"),
                    ("hired", "Hired"),
                    ("not_hired", "Not hired"),
                    ("collaboration_started", "Collaboration started"),
                    ("collaboration_completed", "Collaboration completed"),
                    ("referral_made", "Referral made"),
                    ("referral_accepted", "Referral accepted"),
                    ("not_pursued", "Not pursued"),
                    ("withdrew", "Withdrew"),
                ],
                default="",
                max_length=40,
            ),
        ),
        migrations.AddField(
            model_name="match",
            name="recommendation_verdict",
            field=models.CharField(
                choices=[
                    ("unknown", "Unknown"),
                    ("accurate", "Accurate"),
                    ("partially_accurate", "Partially accurate"),
                    ("inaccurate", "Inaccurate"),
                    ("uncertain", "Uncertain"),
                ],
                default="unknown",
                max_length=24,
            ),
        ),
        migrations.CreateModel(
            name="MatchFeedbackEvent",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Last Modified At")),
                ("id", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ("event_kind", models.CharField(choices=[("recommendation_feedback", "Recommendation feedback"), ("lifecycle_outcome", "Lifecycle outcome")], max_length=32)),
                ("action", models.CharField(choices=[("record", "Record"), ("correct", "Correct"), ("retract", "Retract")], max_length=16)),
                ("verdict", models.CharField(blank=True, choices=[("unknown", "Unknown"), ("accurate", "Accurate"), ("partially_accurate", "Partially accurate"), ("inaccurate", "Inaccurate"), ("uncertain", "Uncertain")], default="", max_length=24)),
                ("outcome_code", models.CharField(blank=True, choices=[("contact_attempted", "Contact attempted"), ("contact_reached", "Contact reached"), ("interview_scheduled", "Interview scheduled"), ("interview_completed", "Interview completed"), ("deal_won", "Deal won"), ("deal_lost", "Deal lost"), ("hired", "Hired"), ("not_hired", "Not hired"), ("collaboration_started", "Collaboration started"), ("collaboration_completed", "Collaboration completed"), ("referral_made", "Referral made"), ("referral_accepted", "Referral accepted"), ("not_pursued", "Not pursued"), ("withdrew", "Withdrew")], default="", max_length=40)),
                ("reason_code", models.CharField(max_length=64)),
                ("note", models.CharField(blank=True, max_length=1000)),
                ("occurred_at", models.DateTimeField()),
                ("recorded_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("source", models.CharField(choices=[("manual", "Manual"), ("crm", "CRM"), ("email", "Email"), ("whatsapp", "WhatsApp"), ("linkedin", "LinkedIn"), ("ats", "ATS"), ("system", "System"), ("import", "Import"), ("other", "Other")], default="manual", max_length=16)),
                ("expected_feedback_revision", models.PositiveBigIntegerField()),
                ("resulting_feedback_revision", models.PositiveBigIntegerField()),
                ("based_on_ranking_revision", models.PositiveBigIntegerField()),
                ("idempotency_key", models.UUIDField()),
                ("request_hash", models.CharField(max_length=64)),
                ("safe_snapshot", models.JSONField(default=dict)),
                ("actor", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="match_feedback_events", to="common.profile")),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(class)s_created_by", to=settings.AUTH_USER_MODEL, verbose_name="Created By")),
                ("match", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="feedback_events", to="matching.match")),
                ("match_revision", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="feedback_events", to="matching.matchrevision")),
                ("org", models.ForeignKey(help_text="Organization this record belongs to", on_delete=django.db.models.deletion.CASCADE, related_name="%(class)s_set", to="common.org")),
                ("supersedes", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="corrections", to="matching.matchfeedbackevent")),
                ("updated_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(class)s_updated_by", to=settings.AUTH_USER_MODEL, verbose_name="Last Modified By")),
            ],
            options={"db_table": "matching_match_feedback_event", "ordering": ("-occurred_at", "-recorded_at")},
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name="MatchFeedbackAttribution",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Last Modified At")),
                ("id", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ("dimension", models.CharField(choices=[("skills", "Skills"), ("titles", "Titles"), ("locations", "Locations"), ("availability", "Availability"), ("trust", "Trust"), ("relationship", "Relationship")], max_length=24)),
                ("assessment", models.CharField(choices=[("helpful", "Helpful"), ("neutral", "Neutral"), ("misleading", "Misleading"), ("outdated", "Outdated"), ("insufficient", "Insufficient")], max_length=24)),
                ("reason_code", models.CharField(blank=True, max_length=64)),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(class)s_created_by", to=settings.AUTH_USER_MODEL, verbose_name="Created By")),
                ("evidence", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="feedback_attributions", to="matching.evidence")),
                ("feedback_event", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="attributions", to="matching.matchfeedbackevent")),
                ("org", models.ForeignKey(help_text="Organization this record belongs to", on_delete=django.db.models.deletion.CASCADE, related_name="%(class)s_set", to="common.org")),
                ("updated_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(class)s_updated_by", to=settings.AUTH_USER_MODEL, verbose_name="Last Modified By")),
            ],
            options={"db_table": "matching_match_feedback_attribution", "ordering": ("dimension", "id")},
            bases=(models.Model,),
        ),
        migrations.AddIndex(model_name="matchfeedbackevent", index=models.Index(fields=["org", "match", "-occurred_at"], name="matching_ma_org_id_a6b0b6_idx")),
        migrations.AddIndex(model_name="matchfeedbackevent", index=models.Index(fields=["org", "event_kind", "-occurred_at"], name="matching_ma_org_id_ef629c_idx")),
        migrations.AddConstraint(model_name="matchfeedbackevent", constraint=models.UniqueConstraint(fields=("org", "idempotency_key"), name="unique_matching_feedback_idempotency")),
        migrations.AddConstraint(model_name="matchfeedbackevent", constraint=models.UniqueConstraint(fields=("org", "match", "resulting_feedback_revision"), name="unique_matching_feedback_revision")),
        migrations.AddConstraint(model_name="matchfeedbackevent", constraint=models.CheckConstraint(condition=models.Q(("resulting_feedback_revision", django.db.models.expressions.CombinedExpression(models.F("expected_feedback_revision"), "+", models.Value(1)))), name="matching_feedback_revision_increments")),
        migrations.AddConstraint(model_name="matchfeedbackevent", constraint=models.CheckConstraint(condition=models.Q(("reason_code", ""), _negated=True), name="matching_feedback_reason_present")),
        migrations.AddIndex(model_name="matchfeedbackattribution", index=models.Index(fields=["org", "feedback_event", "dimension"], name="matching_ma_org_id_a761dd_idx")),
        migrations.AddConstraint(model_name="matchfeedbackattribution", constraint=models.UniqueConstraint(fields=("feedback_event", "evidence", "dimension"), name="unique_matching_feedback_attribution")),
        migrations.RunPython(enable_feedback_security, disable_feedback_security),
    ]
