# Generated by Django 6.0.7 on 2026-08-26 07:00

import django.db.models.deletion
import django.db.models.expressions
import django.utils.timezone
import matching.models
import uuid
from django.conf import settings
from django.db import migrations, models

from common.rls import get_disable_policy_sql, get_enable_policy_sql


RLS_TABLES = (
    "matching_scoring_policy",
    "matching_scoring_policy_version",
    "matching_scoring_policy_event",
    "matching_weight_suggestion",
    "matching_weight_suggestion_review_event",
)


CREATE_SCORING_GUARDS_SQL = r"""
CREATE OR REPLACE FUNCTION matching_validate_scoring_child()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    IF TG_TABLE_NAME = 'matching_scoring_policy' THEN
        IF NEW.active_version_id IS NOT NULL AND NOT EXISTS (
            SELECT 1 FROM matching_scoring_policy_version v
            WHERE v.id = NEW.active_version_id
              AND v.org_id = NEW.org_id
              AND v.policy_id = NEW.id
              AND v.source <> 'ai_suggestion'
        ) THEN
            RAISE EXCEPTION 'AI suggestion cannot be activated directly'
                USING ERRCODE = '23514';
        END IF;
    ELSIF TG_TABLE_NAME = 'matching_scoring_policy_version' THEN
        IF NOT EXISTS (
            SELECT 1 FROM matching_scoring_policy p
            WHERE p.id = NEW.policy_id AND p.org_id = NEW.org_id
        ) THEN
            RAISE EXCEPTION 'matching scoring child organization mismatch'
                USING ERRCODE = '23514';
        END IF;
        IF NEW.created_by_profile_id IS NOT NULL AND NOT EXISTS (
            SELECT 1 FROM profile p
            WHERE p.id = NEW.created_by_profile_id AND p.org_id = NEW.org_id
        ) THEN
            RAISE EXCEPTION 'matching scoring child organization mismatch'
                USING ERRCODE = '23514';
        END IF;
    ELSIF TG_TABLE_NAME = 'matching_scoring_policy_event' THEN
        IF NEW.action IN ('published', 'rejected') AND NEW.actor_id IS NULL THEN
            RAISE EXCEPTION 'scoring policy publication requires a human actor'
                USING ERRCODE = '23514';
        END IF;
        IF NOT EXISTS (
            SELECT 1
            FROM matching_scoring_policy p
            JOIN matching_scoring_policy_version v
              ON v.id = NEW.policy_version_id
             AND v.policy_id = p.id
             AND v.org_id = NEW.org_id
            WHERE p.id = NEW.policy_id
              AND p.org_id = NEW.org_id
              AND p.revision = NEW.resulting_revision
              AND NOT (NEW.action = 'published' AND v.source = 'ai_suggestion')
        ) THEN
            RAISE EXCEPTION 'matching scoring projection mismatch'
                USING ERRCODE = '23514';
        END IF;
        IF NEW.actor_id IS NOT NULL AND NOT EXISTS (
            SELECT 1 FROM profile p
            WHERE p.id = NEW.actor_id AND p.org_id = NEW.org_id
        ) THEN
            RAISE EXCEPTION 'matching scoring child organization mismatch'
                USING ERRCODE = '23514';
        END IF;
    ELSIF TG_TABLE_NAME = 'matching_weight_suggestion' THEN
        IF NOT EXISTS (
            SELECT 1 FROM matching_scoring_policy p
            WHERE p.id = NEW.policy_id AND p.org_id = NEW.org_id
              AND p.opportunity_type = NEW.opportunity_type
        ) THEN
            RAISE EXCEPTION 'matching scoring child organization mismatch'
                USING ERRCODE = '23514';
        END IF;
        IF NEW.reviewed_by_id IS NOT NULL AND NOT EXISTS (
            SELECT 1 FROM profile p
            WHERE p.id = NEW.reviewed_by_id AND p.org_id = NEW.org_id
        ) THEN
            RAISE EXCEPTION 'matching scoring child organization mismatch'
                USING ERRCODE = '23514';
        END IF;
        IF NEW.accepted_draft_id IS NOT NULL AND NOT EXISTS (
            SELECT 1 FROM matching_scoring_policy_version v
            WHERE v.id = NEW.accepted_draft_id
              AND v.org_id = NEW.org_id
              AND v.policy_id = NEW.policy_id
              AND v.source = 'human'
        ) THEN
            RAISE EXCEPTION 'AI suggestion acceptance must create a human draft'
                USING ERRCODE = '23514';
        END IF;
    ELSIF TG_TABLE_NAME = 'matching_weight_suggestion_review_event' THEN
        IF NOT EXISTS (
            SELECT 1 FROM matching_weight_suggestion s
            WHERE s.id = NEW.suggestion_id
              AND s.org_id = NEW.org_id
              AND s.revision = NEW.resulting_revision
        ) THEN
            RAISE EXCEPTION 'matching scoring projection mismatch'
                USING ERRCODE = '23514';
        END IF;
        IF NOT EXISTS (
            SELECT 1 FROM profile p
            WHERE p.id = NEW.actor_id AND p.org_id = NEW.org_id
        ) THEN
            RAISE EXCEPTION 'matching scoring child organization mismatch'
                USING ERRCODE = '23514';
        END IF;
    ELSIF TG_TABLE_NAME = 'matching_opportunity'
          AND NEW.scoring_policy_version_id IS NOT NULL THEN
        IF NOT EXISTS (
            SELECT 1
            FROM matching_scoring_policy_version v
            JOIN matching_scoring_policy p ON p.id = v.policy_id
            WHERE v.id = NEW.scoring_policy_version_id
              AND v.org_id = NEW.org_id
              AND p.org_id = NEW.org_id
              AND p.opportunity_type = NEW.opportunity_type
        ) THEN
            RAISE EXCEPTION 'matching scoring child organization mismatch'
                USING ERRCODE = '23514';
        END IF;
    ELSIF TG_TABLE_NAME IN ('matching_match', 'matching_match_run')
          AND NEW.scoring_policy_version_id IS NOT NULL THEN
        IF NOT EXISTS (
            SELECT 1
            FROM matching_scoring_policy_version v
            JOIN matching_scoring_policy p ON p.id = v.policy_id
            JOIN matching_opportunity o ON o.id = NEW.opportunity_id
            WHERE v.id = NEW.scoring_policy_version_id
              AND v.org_id = NEW.org_id
              AND p.org_id = NEW.org_id
              AND o.org_id = NEW.org_id
              AND p.opportunity_type = o.opportunity_type
        ) THEN
            RAISE EXCEPTION 'matching scoring child organization mismatch'
                USING ERRCODE = '23514';
        END IF;
    ELSIF TG_TABLE_NAME = 'matching_match_revision'
          AND NEW.scoring_policy_version_id IS NOT NULL THEN
        IF NOT EXISTS (
            SELECT 1
            FROM matching_scoring_policy_version v
            JOIN matching_scoring_policy p ON p.id = v.policy_id
            JOIN matching_match m ON m.id = NEW.match_id
            JOIN matching_opportunity o ON o.id = m.opportunity_id
            WHERE v.id = NEW.scoring_policy_version_id
              AND v.org_id = NEW.org_id
              AND p.org_id = NEW.org_id
              AND m.org_id = NEW.org_id
              AND o.org_id = NEW.org_id
              AND p.opportunity_type = o.opportunity_type
        ) THEN
            RAISE EXCEPTION 'matching scoring child organization mismatch'
                USING ERRCODE = '23514';
        END IF;
    END IF;
    RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION matching_reject_scoring_history_mutation()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    RAISE EXCEPTION 'matching scoring history is append-only'
        USING ERRCODE = '55000';
END;
$$;

CREATE TRIGGER matching_scoring_policy_guard
BEFORE INSERT OR UPDATE ON matching_scoring_policy
FOR EACH ROW EXECUTE FUNCTION matching_validate_scoring_child();
CREATE TRIGGER matching_scoring_version_guard
BEFORE INSERT ON matching_scoring_policy_version
FOR EACH ROW EXECUTE FUNCTION matching_validate_scoring_child();
CREATE TRIGGER matching_scoring_event_guard
BEFORE INSERT ON matching_scoring_policy_event
FOR EACH ROW EXECUTE FUNCTION matching_validate_scoring_child();
CREATE TRIGGER matching_weight_suggestion_guard
BEFORE INSERT OR UPDATE ON matching_weight_suggestion
FOR EACH ROW EXECUTE FUNCTION matching_validate_scoring_child();
CREATE TRIGGER matching_weight_review_guard
BEFORE INSERT ON matching_weight_suggestion_review_event
FOR EACH ROW EXECUTE FUNCTION matching_validate_scoring_child();
CREATE TRIGGER matching_opportunity_scoring_guard
BEFORE INSERT OR UPDATE ON matching_opportunity
FOR EACH ROW EXECUTE FUNCTION matching_validate_scoring_child();
CREATE TRIGGER matching_match_scoring_guard
BEFORE INSERT OR UPDATE ON matching_match
FOR EACH ROW EXECUTE FUNCTION matching_validate_scoring_child();
CREATE TRIGGER matching_match_run_scoring_guard
BEFORE INSERT OR UPDATE ON matching_match_run
FOR EACH ROW EXECUTE FUNCTION matching_validate_scoring_child();
CREATE TRIGGER matching_match_revision_scoring_guard
BEFORE INSERT ON matching_match_revision
FOR EACH ROW EXECUTE FUNCTION matching_validate_scoring_child();
CREATE TRIGGER matching_scoring_version_append_only
BEFORE UPDATE OR DELETE ON matching_scoring_policy_version
FOR EACH ROW EXECUTE FUNCTION matching_reject_scoring_history_mutation();
CREATE TRIGGER matching_scoring_event_append_only
BEFORE UPDATE OR DELETE ON matching_scoring_policy_event
FOR EACH ROW EXECUTE FUNCTION matching_reject_scoring_history_mutation();
CREATE TRIGGER matching_weight_review_append_only
BEFORE UPDATE OR DELETE ON matching_weight_suggestion_review_event
FOR EACH ROW EXECUTE FUNCTION matching_reject_scoring_history_mutation();
"""


DROP_SCORING_GUARDS_SQL = r"""
DROP TRIGGER IF EXISTS matching_weight_review_append_only ON matching_weight_suggestion_review_event;
DROP TRIGGER IF EXISTS matching_scoring_event_append_only ON matching_scoring_policy_event;
DROP TRIGGER IF EXISTS matching_scoring_version_append_only ON matching_scoring_policy_version;
DROP TRIGGER IF EXISTS matching_match_revision_scoring_guard ON matching_match_revision;
DROP TRIGGER IF EXISTS matching_match_run_scoring_guard ON matching_match_run;
DROP TRIGGER IF EXISTS matching_match_scoring_guard ON matching_match;
DROP TRIGGER IF EXISTS matching_opportunity_scoring_guard ON matching_opportunity;
DROP TRIGGER IF EXISTS matching_weight_review_guard ON matching_weight_suggestion_review_event;
DROP TRIGGER IF EXISTS matching_weight_suggestion_guard ON matching_weight_suggestion;
DROP TRIGGER IF EXISTS matching_scoring_event_guard ON matching_scoring_policy_event;
DROP TRIGGER IF EXISTS matching_scoring_version_guard ON matching_scoring_policy_version;
DROP TRIGGER IF EXISTS matching_scoring_policy_guard ON matching_scoring_policy;
DROP FUNCTION IF EXISTS matching_reject_scoring_history_mutation();
DROP FUNCTION IF EXISTS matching_validate_scoring_child();
"""


def enable_scoring_security(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    with schema_editor.connection.cursor() as cursor:
        for table in RLS_TABLES:
            cursor.execute(get_enable_policy_sql(table))
        cursor.execute(CREATE_SCORING_GUARDS_SQL)


def disable_scoring_security(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(DROP_SCORING_GUARDS_SQL)
        for table in reversed(RLS_TABLES):
            cursor.execute(get_disable_policy_sql(table))


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0030_profile_matching_access_level'),
        ('matching', '0007_match_feedback_loop'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='scoring_policy_checksum',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='matchrevision',
            name='component_weights',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='matchrevision',
            name='dimension_weights',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='matchrevision',
            name='scoring_policy_checksum',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='matchrun',
            name='component_weights',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='matchrun',
            name='dimension_weights',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='matchrun',
            name='scoring_policy_checksum',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.CreateModel(
            name='MatchScoringPolicy',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('opportunity_type', models.CharField(choices=[('customer', 'Customer'), ('employment', 'Employment'), ('contractor', 'Contractor'), ('project', 'Project'), ('expert', 'Expert'), ('referral', 'Referral'), ('partnership', 'Partnership')], max_length=24)),
                ('revision', models.PositiveBigIntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('org', models.ForeignKey(help_text='Organization this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='common.org')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
            ],
            options={
                'db_table': 'matching_scoring_policy',
                'ordering': ('opportunity_type',),
            },
        ),
        migrations.CreateModel(
            name='MatchScoringPolicyVersion',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('version', models.PositiveIntegerField()),
                ('dimension_weights', models.JSONField(default=matching.models.default_scoring_weights)),
                ('component_weights', models.JSONField(default=dict)),
                ('checksum', models.CharField(max_length=64)),
                ('source', models.CharField(choices=[('human', 'Human'), ('ai_suggestion', 'AI suggestion'), ('legacy', 'Legacy')], default='human', max_length=24)),
                ('rationale', models.CharField(blank=True, max_length=1000)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('created_by_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_match_scoring_versions', to='common.profile')),
                ('org', models.ForeignKey(help_text='Organization this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='common.org')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='matching.matchscoringpolicy')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
            ],
            options={
                'db_table': 'matching_scoring_policy_version',
                'ordering': ('-version',),
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='MatchScoringPolicyEvent',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('action', models.CharField(choices=[('draft_created', 'Draft created'), ('published', 'Published'), ('rejected', 'Rejected')], max_length=24)),
                ('expected_revision', models.PositiveBigIntegerField()),
                ('resulting_revision', models.PositiveBigIntegerField()),
                ('idempotency_key', models.UUIDField()),
                ('request_hash', models.CharField(max_length=64)),
                ('reason_code', models.CharField(blank=True, max_length=64)),
                ('safe_snapshot', models.JSONField(default=dict)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='match_scoring_policy_events', to='common.profile')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('org', models.ForeignKey(help_text='Organization this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='common.org')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='matching.matchscoringpolicy')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('policy_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='matching.matchscoringpolicyversion')),
            ],
            options={
                'db_table': 'matching_scoring_policy_event',
                'ordering': ('-created_at',),
            },
            bases=(models.Model,),
        ),
        migrations.AddField(
            model_name='matchscoringpolicy',
            name='active_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='active_for_policies', to='matching.matchscoringpolicyversion'),
        ),
        migrations.AddField(
            model_name='match',
            name='scoring_policy_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='matches', to='matching.matchscoringpolicyversion'),
        ),
        migrations.AddField(
            model_name='matchopportunity',
            name='scoring_policy_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='opportunities', to='matching.matchscoringpolicyversion'),
        ),
        migrations.AddField(
            model_name='matchrevision',
            name='scoring_policy_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='match_revisions', to='matching.matchscoringpolicyversion'),
        ),
        migrations.AddField(
            model_name='matchrun',
            name='scoring_policy_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='match_runs', to='matching.matchscoringpolicyversion'),
        ),
        migrations.CreateModel(
            name='MatchWeightSuggestion',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('opportunity_type', models.CharField(choices=[('customer', 'Customer'), ('employment', 'Employment'), ('contractor', 'Contractor'), ('project', 'Project'), ('expert', 'Expert'), ('referral', 'Referral'), ('partnership', 'Partnership')], max_length=24)),
                ('dimension_weights', models.JSONField(default=matching.models.default_scoring_weights)),
                ('component_weights', models.JSONField(default=dict)),
                ('rationale', models.CharField(blank=True, max_length=1000)),
                ('sample_count', models.PositiveIntegerField(default=0)),
                ('analysis_hash', models.CharField(max_length=64)),
                ('base_policy_checksum', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=16)),
                ('revision', models.PositiveBigIntegerField(default=0)),
                ('generator', models.CharField(blank=True, max_length=120)),
                ('idempotency_key', models.UUIDField()),
                ('request_hash', models.CharField(max_length=64)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_draft', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accepted_suggestions', to='matching.matchscoringpolicyversion')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('org', models.ForeignKey(help_text='Organization this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='common.org')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='weight_suggestions', to='matching.matchscoringpolicy')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_match_weight_suggestions', to='common.profile')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
            ],
            options={
                'db_table': 'matching_weight_suggestion',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='MatchWeightSuggestionReviewEvent',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('action', models.CharField(choices=[('accept', 'Accept'), ('reject', 'Reject')], max_length=16)),
                ('expected_revision', models.PositiveBigIntegerField()),
                ('resulting_revision', models.PositiveBigIntegerField()),
                ('idempotency_key', models.UUIDField()),
                ('request_hash', models.CharField(max_length=64)),
                ('reason_code', models.CharField(blank=True, max_length=64)),
                ('safe_snapshot', models.JSONField(default=dict)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='match_weight_suggestion_reviews', to='common.profile')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('org', models.ForeignKey(help_text='Organization this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='common.org')),
                ('suggestion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='review_events', to='matching.matchweightsuggestion')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
            ],
            options={
                'db_table': 'matching_weight_suggestion_review_event',
                'ordering': ('-created_at',),
            },
            bases=(models.Model,),
        ),
        migrations.AddIndex(
            model_name='matchscoringpolicyversion',
            index=models.Index(fields=['org', 'policy', '-version'], name='matching_sc_org_id_b0bef7_idx'),
        ),
        migrations.AddConstraint(
            model_name='matchscoringpolicyversion',
            constraint=models.UniqueConstraint(fields=('org', 'policy', 'version'), name='unique_matching_policy_version'),
        ),
        migrations.AddConstraint(
            model_name='matchscoringpolicyevent',
            constraint=models.UniqueConstraint(fields=('org', 'idempotency_key'), name='unique_matching_policy_event_key'),
        ),
        migrations.AddConstraint(
            model_name='matchscoringpolicyevent',
            constraint=models.UniqueConstraint(fields=('org', 'policy', 'resulting_revision'), name='unique_matching_policy_event_revision'),
        ),
        migrations.AddConstraint(
            model_name='matchscoringpolicyevent',
            constraint=models.CheckConstraint(condition=models.Q(('resulting_revision', django.db.models.expressions.CombinedExpression(models.F('expected_revision'), '+', models.Value(1)))), name='matching_policy_event_revision_increments'),
        ),
        migrations.AddConstraint(
            model_name='matchscoringpolicy',
            constraint=models.UniqueConstraint(fields=('org', 'opportunity_type'), name='unique_matching_scoring_policy_type'),
        ),
        migrations.AddIndex(
            model_name='matchweightsuggestion',
            index=models.Index(fields=['org', 'status', '-created_at'], name='matching_we_org_id_ddbb0d_idx'),
        ),
        migrations.AddConstraint(
            model_name='matchweightsuggestion',
            constraint=models.UniqueConstraint(fields=('org', 'analysis_hash'), name='unique_matching_weight_suggestion_analysis'),
        ),
        migrations.AddConstraint(
            model_name='matchweightsuggestion',
            constraint=models.UniqueConstraint(fields=('org', 'idempotency_key'), name='unique_matching_weight_suggestion_key'),
        ),
        migrations.AddConstraint(
            model_name='matchweightsuggestionreviewevent',
            constraint=models.UniqueConstraint(fields=('org', 'idempotency_key'), name='unique_matching_suggestion_review_key'),
        ),
        migrations.AddConstraint(
            model_name='matchweightsuggestionreviewevent',
            constraint=models.UniqueConstraint(fields=('org', 'suggestion', 'resulting_revision'), name='unique_matching_suggestion_review_revision'),
        ),
        migrations.AddConstraint(
            model_name='matchweightsuggestionreviewevent',
            constraint=models.CheckConstraint(condition=models.Q(('resulting_revision', django.db.models.expressions.CombinedExpression(models.F('expected_revision'), '+', models.Value(1)))), name='matching_suggestion_review_revision_increments'),
        ),
        migrations.RunPython(enable_scoring_security, disable_scoring_security),
    ]
