# Generated by Django 6.0.7 on 2026-07-29 09:37

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

from common.rls import get_disable_policy_sql, get_enable_policy_sql


def enable_intake_rls(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(get_enable_policy_sql("sdr_lead_intake"))


def disable_intake_rls(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(get_disable_policy_sql("sdr_lead_intake"))


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("common", "0029_delete_sessiontoken"),
        ("leads", "0013_lead_custom_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LeadIntake",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Last Modified At"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("facebook_ad", "Facebook Lead Ad"),
                            ("website_form", "Website Form"),
                            ("linkedin", "LinkedIn"),
                            ("email", "Email"),
                            ("api", "API"),
                            ("manual", "Manual"),
                        ],
                        max_length=32,
                    ),
                ),
                ("source_record_id", models.CharField(max_length=255)),
                ("raw_payload", models.JSONField(default=dict)),
                ("normalized_payload", models.JSONField(default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("received", "Received"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="received",
                        max_length=16,
                    ),
                ),
                ("attempt_count", models.PositiveIntegerField(default=0)),
                ("error_message", models.TextField(blank=True)),
                (
                    "qualification_score",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("qualification_band", models.CharField(blank=True, max_length=32)),
                ("matched_existing", models.BooleanField(default=False)),
                ("crm_created", models.BooleanField(blank=True, null=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "assigned_profile",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sdr_intakes",
                        to="common.profile",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "crm_lead",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sdr_intakes",
                        to="leads.lead",
                    ),
                ),
                (
                    "org",
                    models.ForeignKey(
                        help_text="Organization this record belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="common.org",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Last Modified By",
                    ),
                ),
            ],
            options={
                "db_table": "sdr_lead_intake",
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["org", "status", "-created_at"],
                        name="sdr_lead_in_org_id_60cca7_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("org", "source", "source_record_id"),
                        name="unique_sdr_intake_source_record_per_org",
                    )
                ],
            },
        ),
        migrations.RunPython(enable_intake_rls, disable_intake_rls),
    ]
