# Generated by Django 6.0.7 on 2026-07-29 14:05

import uuid

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

from common.rls import get_disable_policy_sql, get_enable_policy_sql

TABLES = (
    "sdr_nurture_sequence",
    "sdr_nurture_step",
    "sdr_nurture_enrollment",
    "sdr_nurture_delivery",
)


def enable_nurture_rls(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    with schema_editor.connection.cursor() as cursor:
        for table in TABLES:
            cursor.execute(get_enable_policy_sql(table))


def disable_nurture_rls(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    with schema_editor.connection.cursor() as cursor:
        for table in TABLES:
            cursor.execute(get_disable_policy_sql(table))


def audit_fields():
    return [
        ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
        ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Last Modified At")),
        (
            "id",
            models.UUIDField(
                db_index=True,
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]


def audit_relationship_fields():
    return [
        (
            "created_by",
            models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created_by",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created By",
            ),
        ),
        (
            "updated_by",
            models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_updated_by",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Last Modified By",
            ),
        ),
    ]


def org_field():
    return (
        "org",
        models.ForeignKey(
            help_text="Organization this record belongs to",
            on_delete=django.db.models.deletion.CASCADE,
            related_name="%(class)s_set",
            to="common.org",
        ),
    )


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0029_delete_sessiontoken"),
        ("leads", "0013_lead_custom_fields"),
        ("sdr", "0005_lead_response_loop"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="leadlifecycleevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("received", "Received"),
                    ("queued", "Queued"),
                    ("processing", "Processing"),
                    ("qualified", "Qualified"),
                    ("assigned", "Assigned"),
                    ("crm_handoff", "CRM handoff"),
                    ("acknowledgement_sent", "Acknowledgement sent"),
                    ("sales_notified", "Sales notified"),
                    ("nurture_enrolled", "Nurture enrolled"),
                    ("nurture_email_sent", "Nurture email sent"),
                    ("nurture_stopped", "Nurture stopped"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                ],
                max_length=40,
            ),
        ),
        migrations.CreateModel(
            name="SDRNurtureSequence",
            fields=audit_fields()
            + [
                ("name", models.CharField(max_length=160)),
                ("description", models.TextField(blank=True)),
                ("priority", models.PositiveIntegerField(default=100)),
                ("is_active", models.BooleanField(default=False)),
                ("auto_enroll", models.BooleanField(default=False)),
                ("sources", models.JSONField(blank=True, default=list)),
                (
                    "qualification_bands",
                    models.JSONField(blank=True, default=list),
                ),
                ("from_email", models.EmailField(blank=True, max_length=254)),
            ]
            + audit_relationship_fields()
            + [org_field()],
            options={
                "db_table": "sdr_nurture_sequence",
                "ordering": ("priority", "created_at", "id"),
            },
        ),
        migrations.CreateModel(
            name="LeadNurtureEnrollment",
            fields=audit_fields()
            + [
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("paused", "Paused"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("replied", "Replied"),
                            ("converted", "Converted"),
                        ],
                        default="active",
                        max_length=16,
                    ),
                ),
                ("current_step_position", models.PositiveSmallIntegerField(default=0)),
                ("resume_count", models.PositiveIntegerField(default=0)),
                ("next_run_at", models.DateTimeField(blank=True, null=True)),
                (
                    "enrolled_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("stop_reason", models.CharField(blank=True, max_length=500)),
            ]
            + audit_relationship_fields()
            + [
                (
                    "intake",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nurture_enrollment",
                        to="sdr.leadintake",
                    ),
                ),
                (
                    "lead",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sdr_nurture_enrollments",
                        to="leads.lead",
                    ),
                ),
                org_field(),
                (
                    "sequence",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="enrollments",
                        to="sdr.sdrnurturesequence",
                    ),
                ),
            ],
            options={
                "db_table": "sdr_nurture_enrollment",
                "ordering": ("-enrolled_at", "-created_at"),
            },
        ),
        migrations.CreateModel(
            name="SDRNurtureStep",
            fields=audit_fields()
            + [
                ("position", models.PositiveSmallIntegerField()),
                (
                    "delay_minutes",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Delay after enrollment or the preceding successful step.",
                        validators=[django.core.validators.MaxValueValidator(525600)],
                    ),
                ),
                ("subject_a", models.CharField(max_length=255)),
                ("body_a", models.TextField()),
                ("subject_b", models.CharField(blank=True, max_length=255)),
                ("body_b", models.TextField(blank=True)),
                (
                    "variant_b_percent",
                    models.PositiveSmallIntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
            ]
            + audit_relationship_fields()
            + [
                org_field(),
                (
                    "sequence",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="sdr.sdrnurturesequence",
                    ),
                ),
            ],
            options={
                "db_table": "sdr_nurture_step",
                "ordering": ("position", "created_at", "id"),
            },
        ),
        migrations.CreateModel(
            name="LeadNurtureDelivery",
            fields=audit_fields()
            + [
                ("step_position", models.PositiveSmallIntegerField()),
                (
                    "variant",
                    models.CharField(
                        choices=[("A", "A"), ("B", "B")],
                        default="A",
                        max_length=1,
                    ),
                ),
                ("recipient", models.EmailField(max_length=254)),
                ("subject_template", models.CharField(max_length=255)),
                ("body_template", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sending", "Sending"),
                            ("sent", "Sent"),
                            ("failed", "Failed"),
                            ("skipped", "Skipped"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("scheduled_for", models.DateTimeField()),
                ("attempt_count", models.PositiveIntegerField(default=0)),
                ("last_error_code", models.CharField(blank=True, max_length=80)),
                ("last_error_message", models.TextField(blank=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("replied_at", models.DateTimeField(blank=True, null=True)),
                (
                    "reply_sentiment",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("positive", "Positive"),
                            ("neutral", "Neutral"),
                            ("negative", "Negative"),
                        ],
                        max_length=16,
                    ),
                ),
            ]
            + audit_relationship_fields()
            + [
                (
                    "enrollment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deliveries",
                        to="sdr.leadnurtureenrollment",
                    ),
                ),
                org_field(),
                (
                    "step",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="deliveries",
                        to="sdr.sdrnurturestep",
                    ),
                ),
            ],
            options={
                "db_table": "sdr_nurture_delivery",
                "ordering": ("scheduled_for", "created_at", "id"),
            },
        ),
        migrations.AddIndex(
            model_name="sdrnurturesequence",
            index=models.Index(
                fields=["org", "is_active", "auto_enroll", "priority"],
                name="sdr_nurture_org_active_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="leadnurtureenrollment",
            index=models.Index(
                fields=["org", "status", "next_run_at"],
                name="sdr_nurture_enroll_status_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="sdrnurturestep",
            index=models.Index(
                fields=["org", "sequence", "position"],
                name="sdr_nurture_step_org_seq_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="sdrnurturestep",
            constraint=models.UniqueConstraint(
                fields=("org", "sequence", "position"),
                name="unique_sdr_nurture_step_position",
            ),
        ),
        migrations.AddIndex(
            model_name="leadnurturedelivery",
            index=models.Index(
                fields=["org", "status", "scheduled_for"],
                name="sdr_nurture_delivery_due_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="leadnurturedelivery",
            index=models.Index(
                fields=["org", "variant", "sent_at"],
                name="sdr_nurture_variant_sent_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="leadnurturedelivery",
            constraint=models.UniqueConstraint(
                fields=("org", "enrollment", "step_position"),
                name="unique_sdr_nurture_delivery_step",
            ),
        ),
        migrations.RunPython(enable_nurture_rls, disable_nurture_rls),
    ]
