# Generated by Django 6.0.7 on 2026-07-30 12:26

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

from common.rls import get_disable_policy_sql, get_enable_policy_sql


def enable_interaction_rls(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(get_enable_policy_sql("sdr_nurture_interaction"))


def disable_interaction_rls(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(get_disable_policy_sql("sdr_nurture_interaction"))


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0029_delete_sessiontoken"),
        ("sdr", "0007_inbound_email_reply"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="leadnurturedelivery",
            name="click_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="leadnurturedelivery",
            name="clicked_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="leadnurturedelivery",
            name="last_clicked_url",
            field=models.URLField(blank=True, max_length=2048),
        ),
        migrations.AddField(
            model_name="leadnurturedelivery",
            name="open_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="leadnurturedelivery",
            name="opened_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="leadlifecycleevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("received", "Received"),
                    ("queued", "Queued"),
                    ("processing", "Processing"),
                    ("qualified", "Qualified"),
                    ("assigned", "Assigned"),
                    ("crm_handoff", "CRM handoff"),
                    ("acknowledgement_sent", "Acknowledgement sent"),
                    ("sales_notified", "Sales notified"),
                    ("nurture_enrolled", "Nurture enrolled"),
                    ("nurture_email_sent", "Nurture email sent"),
                    ("nurture_email_opened", "Nurture email opened"),
                    ("nurture_link_clicked", "Nurture link clicked"),
                    ("nurture_stopped", "Nurture stopped"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                ],
                max_length=40,
            ),
        ),
        migrations.CreateModel(
            name="LeadNurtureInteraction",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        verbose_name="Last Modified At",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[("open", "Open"), ("click", "Click")],
                        max_length=12,
                    ),
                ),
                ("target_url", models.URLField(blank=True, max_length=2048)),
                ("target_hash", models.CharField(max_length=64)),
                ("visitor_hash", models.CharField(max_length=64)),
                (
                    "occurred_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "delivery",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interactions",
                        to="sdr.leadnurturedelivery",
                    ),
                ),
                (
                    "org",
                    models.ForeignKey(
                        help_text="Organization this record belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="common.org",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Last Modified By",
                    ),
                ),
            ],
            options={
                "db_table": "sdr_nurture_interaction",
                "ordering": ("occurred_at", "created_at", "id"),
                "indexes": [
                    models.Index(
                        fields=["org", "event_type", "-occurred_at"],
                        name="sdr_nurture_interact_event_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=(
                            "org",
                            "delivery",
                            "event_type",
                            "target_hash",
                            "visitor_hash",
                        ),
                        name="unique_sdr_nurture_interaction",
                    )
                ],
            },
        ),
        migrations.RunPython(enable_interaction_rls, disable_interaction_rls),
    ]
