# Generated by Django 6.0.7 on 2026-07-30 12:39

import uuid

import django.db.models.deletion
import django.db.models.functions.text
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

from common.rls import get_disable_policy_sql, get_enable_policy_sql


def enable_suppression_rls(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(get_enable_policy_sql("sdr_email_suppression"))


def disable_suppression_rls(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(get_disable_policy_sql("sdr_email_suppression"))


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0029_delete_sessiontoken"),
        ("sdr", "0008_nurture_tracking"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="leadlifecycleevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("received", "Received"),
                    ("queued", "Queued"),
                    ("processing", "Processing"),
                    ("qualified", "Qualified"),
                    ("assigned", "Assigned"),
                    ("crm_handoff", "CRM handoff"),
                    ("acknowledgement_sent", "Acknowledgement sent"),
                    ("sales_notified", "Sales notified"),
                    ("nurture_enrolled", "Nurture enrolled"),
                    ("nurture_email_sent", "Nurture email sent"),
                    ("nurture_email_opened", "Nurture email opened"),
                    ("nurture_link_clicked", "Nurture link clicked"),
                    ("nurture_suppressed", "Nurture suppressed"),
                    ("nurture_stopped", "Nurture stopped"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                ],
                max_length=40,
            ),
        ),
        migrations.CreateModel(
            name="SDREmailSuppression",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        verbose_name="Last Modified At",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("unsubscribed", "Unsubscribed"),
                            ("complaint", "Spam complaint"),
                            ("hard_bounce", "Hard bounce"),
                            ("invalid", "Invalid address"),
                            ("admin", "Administrator"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("one_click", "One-click unsubscribe"),
                            ("inbound_reply", "Inbound email reply"),
                            ("provider", "Email provider"),
                            ("admin", "Administrator"),
                        ],
                        max_length=24,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "suppressed_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("released_at", models.DateTimeField(blank=True, null=True)),
                ("details", models.JSONField(blank=True, default=dict)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "org",
                    models.ForeignKey(
                        help_text="Organization this record belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="common.org",
                    ),
                ),
                (
                    "source_delivery",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="suppressions",
                        to="sdr.leadnurturedelivery",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Last Modified By",
                    ),
                ),
            ],
            options={
                "db_table": "sdr_email_suppression",
                "ordering": ("-is_active", "-suppressed_at", "email"),
                "indexes": [
                    models.Index(
                        fields=["org", "is_active", "-suppressed_at"],
                        name="sdr_suppression_org_active_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        django.db.models.functions.text.Lower("email"),
                        models.F("org"),
                        name="unique_sdr_email_suppression",
                    )
                ],
            },
        ),
        migrations.RunPython(enable_suppression_rls, disable_suppression_rls),
    ]
