# Generated by Django 6.0.7 on 2026-07-30 12:51

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

from common.rls import get_disable_policy_sql, get_enable_policy_sql


def enable_provider_event_rls(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(get_enable_policy_sql("sdr_email_provider_event"))


def disable_provider_event_rls(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(get_disable_policy_sql("sdr_email_provider_event"))


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0029_delete_sessiontoken"),
        ("sdr", "0009_email_suppression"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="leadnurturedelivery",
            name="bounce_subtype",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="leadnurturedelivery",
            name="bounce_type",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name="leadnurturedelivery",
            name="bounced_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="leadnurturedelivery",
            name="complained_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="leadnurturedelivery",
            name="delivered_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="leadnurturedelivery",
            name="provider_message_id",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="leadlifecycleevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("received", "Received"),
                    ("queued", "Queued"),
                    ("processing", "Processing"),
                    ("qualified", "Qualified"),
                    ("assigned", "Assigned"),
                    ("crm_handoff", "CRM handoff"),
                    ("acknowledgement_sent", "Acknowledgement sent"),
                    ("sales_notified", "Sales notified"),
                    ("nurture_enrolled", "Nurture enrolled"),
                    ("nurture_email_sent", "Nurture email sent"),
                    ("nurture_email_opened", "Nurture email opened"),
                    ("nurture_link_clicked", "Nurture link clicked"),
                    ("nurture_suppressed", "Nurture suppressed"),
                    ("nurture_delivered", "Nurture delivered"),
                    ("nurture_bounced", "Nurture bounced"),
                    ("nurture_complained", "Nurture complained"),
                    ("nurture_stopped", "Nurture stopped"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                ],
                max_length=40,
            ),
        ),
        migrations.CreateModel(
            name="SDREmailProviderEvent",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        verbose_name="Last Modified At",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[("ses", "AWS SES")],
                        default="ses",
                        max_length=24,
                    ),
                ),
                ("provider_event_id", models.CharField(max_length=255)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("delivery", "Delivery"),
                            ("bounce", "Bounce"),
                            ("complaint", "Complaint"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "event_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("details", models.JSONField(blank=True, default=dict)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "delivery",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="provider_events",
                        to="sdr.leadnurturedelivery",
                    ),
                ),
                (
                    "org",
                    models.ForeignKey(
                        help_text="Organization this record belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="common.org",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Last Modified By",
                    ),
                ),
            ],
            options={
                "db_table": "sdr_email_provider_event",
                "ordering": ("-event_at", "-created_at", "id"),
                "indexes": [
                    models.Index(
                        fields=["org", "event_type", "-event_at"],
                        name="sdr_provider_event_org_type_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("org", "provider", "provider_event_id"),
                        name="unique_sdr_email_provider_event",
                    )
                ],
            },
        ),
        migrations.RunPython(enable_provider_event_rls, disable_provider_event_rls),
    ]
