# Generated by Django 6.0.7 on 2026-07-30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("sdr", "0010_ses_delivery_feedback")]

    operations = [
        migrations.AlterField(
            model_name="leadintake",
            name="source",
            field=models.CharField(
                choices=[
                    ("facebook_ad", "Facebook Lead Ad"),
                    ("facebook_messenger", "Facebook Messenger"),
                    ("website_form", "Website Form"),
                    ("linkedin", "LinkedIn"),
                    ("email", "Email"),
                    ("api", "API"),
                    ("manual", "Manual"),
                ],
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="leadlifecycleevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("received", "Received"),
                    ("queued", "Queued"),
                    ("processing", "Processing"),
                    ("qualified", "Qualified"),
                    ("assigned", "Assigned"),
                    ("crm_handoff", "CRM handoff"),
                    ("acknowledgement_sent", "Acknowledgement sent"),
                    ("sales_notified", "Sales notified"),
                    ("nurture_enrolled", "Nurture enrolled"),
                    ("nurture_email_sent", "Nurture email sent"),
                    ("nurture_email_opened", "Nurture email opened"),
                    ("nurture_link_clicked", "Nurture link clicked"),
                    ("nurture_suppressed", "Nurture suppressed"),
                    ("nurture_delivered", "Nurture delivered"),
                    ("nurture_bounced", "Nurture bounced"),
                    ("nurture_complained", "Nurture complained"),
                    ("channel_message_received", "Channel message received"),
                    ("nurture_stopped", "Nurture stopped"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                ],
                max_length=40,
            ),
        ),
    ]
