# Generated by Django 6.0.7 on 2026-08-12 10:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sdr", "0014_email_safety_controls"),
    ]

    operations = [
        migrations.AddField(
            model_name="sdroutboundcampaign",
            name="whatsapp_template_language",
            field=models.CharField(default="en_US", max_length=20),
        ),
        migrations.AddField(
            model_name="sdroutboundcampaign",
            name="whatsapp_template_name",
            field=models.CharField(blank=True, max_length=512),
        ),
    ]
