# Generated by Django 6.0.7 on 2026-08-12 11:11

import uuid

import django.core.validators
import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models

from common.rls import get_disable_policy_sql, get_enable_policy_sql


def enable_outbound_source_rls(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(get_enable_policy_sql("sdr_outbound_source"))


def disable_outbound_source_rls(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(get_disable_policy_sql("sdr_outbound_source"))


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0029_delete_sessiontoken'),
        ('sdr', '0015_sdroutboundcampaign_whatsapp_template_language_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SDROutboundSource',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('provider', models.CharField(choices=[('apollo', 'Apollo')], default='apollo', max_length=24)),
                ('is_active', models.BooleanField(default=False)),
                ('search_filters', models.JSONField(default=dict)),
                ('interval_hours', models.PositiveSmallIntegerField(default=24, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(168)])),
                ('max_results_per_sync', models.PositiveSmallIntegerField(default=25, help_text='Maximum Apollo enrichment requests made by one source sync.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('enrichment_credits_acknowledged', models.BooleanField(default=False)),
                ('next_sync_at', models.DateTimeField(blank=True, null=True)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('last_job_id', models.UUIDField(blank=True, null=True)),
                ('next_page', models.PositiveSmallIntegerField(default=1)),
                ('sync_count', models.PositiveIntegerField(default=0)),
                ('last_sync_stats', models.JSONField(blank=True, default=dict)),
                ('last_error_code', models.CharField(blank=True, max_length=80)),
                ('last_error_message', models.CharField(blank=True, max_length=1000)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='sdr.sdroutboundcampaign')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('org', models.ForeignKey(help_text='Organization this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='common.org')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
            ],
            options={
                'db_table': 'sdr_outbound_source',
                'ordering': ('name', 'created_at'),
                'indexes': [models.Index(fields=['org', 'is_active', 'next_sync_at'], name='sdr_out_source_due_idx')],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('name'), models.F('campaign'), models.F('org'), name='unique_sdr_out_source_name')],
            },
        ),
        migrations.RunPython(enable_outbound_source_rls, disable_outbound_source_rls),
    ]
