# Generated by Django 6.0.7 on 2026-08-12 11:51

import uuid

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

from common.rls import get_disable_policy_sql, get_enable_policy_sql


def enable_outbound_copy_draft_rls(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(get_enable_policy_sql("sdr_outbound_copy_draft"))


def disable_outbound_copy_draft_rls(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(get_disable_policy_sql("sdr_outbound_copy_draft"))


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0029_delete_sessiontoken'),
        ('sdr', '0016_sdroutboundsource'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SDROutboundCopyDraft',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('generating', 'Generating'), ('ready', 'Ready for review'), ('failed', 'Failed'), ('applied', 'Applied')], default='pending', max_length=16)),
                ('language', models.CharField(default='English', max_length=40)),
                ('tone', models.CharField(default='concise and consultative', max_length=80)),
                ('offering_summary', models.TextField()),
                ('value_proposition', models.TextField()),
                ('proof_points', models.TextField(blank=True)),
                ('cta_goal', models.CharField(max_length=500)),
                ('step_count', models.PositiveSmallIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('generated_steps', models.JSONField(blank=True, default=list)),
                ('provider', models.CharField(blank=True, max_length=24)),
                ('model', models.CharField(blank=True, max_length=100)),
                ('prompt_version', models.CharField(blank=True, max_length=80)),
                ('provider_response_id', models.CharField(blank=True, max_length=255)),
                ('provider_attempts', models.JSONField(blank=True, default=list)),
                ('input_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('output_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('last_job_id', models.UUIDField(blank=True, null=True)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, max_length=80)),
                ('error_message', models.CharField(blank=True, max_length=1000)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='copy_drafts', to='sdr.sdroutboundcampaign')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('org', models.ForeignKey(help_text='Organization this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='common.org')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_sdr_outbound_copy_drafts', to='common.profile')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
            ],
            options={
                'db_table': 'sdr_outbound_copy_draft',
                'ordering': ('-created_at', 'id'),
                'indexes': [models.Index(fields=['org', 'campaign', '-created_at'], name='sdr_copy_draft_campaign_idx')],
            },
        ),
        migrations.RunPython(
            enable_outbound_copy_draft_rls,
            disable_outbound_copy_draft_rls,
        ),
    ]
