# Generated by Django 6.0.7 on 2026-08-12 12:26

import uuid

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

from common.rls import get_disable_policy_sql, get_enable_policy_sql


def enable_sales_feedback_rls(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(get_enable_policy_sql("sdr_sales_feedback"))


def disable_sales_feedback_rls(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(get_disable_policy_sql("sdr_sales_feedback"))


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0029_delete_sessiontoken"),
        ("sdr", "0017_outbound_copy_draft"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SDRSalesFeedback",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Last Modified At"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "decision",
                    models.CharField(
                        choices=[
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                            ("recycle", "Recycle / nurture"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("good_fit", "Good fit"),
                            ("wrong_industry", "Wrong industry"),
                            ("wrong_company_size", "Wrong company size"),
                            ("wrong_role", "Wrong contact role"),
                            ("bad_contact", "Invalid or unreachable contact"),
                            ("no_need", "No current need"),
                            ("no_budget", "No budget"),
                            ("bad_timing", "Bad timing"),
                            ("duplicate", "Duplicate"),
                            ("other", "Other"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "quality_score",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ]
                    ),
                ),
                (
                    "satisfaction_score",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ]
                    ),
                ),
                ("notes", models.CharField(blank=True, max_length=1000)),
                (
                    "qualification_score_snapshot",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "qualification_band_snapshot",
                    models.CharField(blank=True, max_length=32),
                ),
                ("provider_snapshot", models.CharField(blank=True, max_length=32)),
                ("model_snapshot", models.CharField(blank=True, max_length=100)),
                (
                    "prompt_version_snapshot",
                    models.CharField(blank=True, max_length=64),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "feedback_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="submitted_sdr_sales_feedback",
                        to="common.profile",
                    ),
                ),
                (
                    "intake",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sales_feedback",
                        to="sdr.leadintake",
                    ),
                ),
                (
                    "org",
                    models.ForeignKey(
                        help_text="Organization this record belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="common.org",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Last Modified By",
                    ),
                ),
            ],
            options={
                "db_table": "sdr_sales_feedback",
                "ordering": ("-submitted_at", "-created_at"),
                "indexes": [
                    models.Index(
                        fields=["org", "decision", "-submitted_at"],
                        name="sdr_feedback_org_decision_idx",
                    ),
                    models.Index(
                        fields=["org", "qualification_band_snapshot", "-submitted_at"],
                        name="sdr_feedback_org_band_idx",
                    ),
                ],
            },
        ),
        migrations.RunPython(enable_sales_feedback_rls, disable_sales_feedback_rls),
    ]
