# Generated by Django 6.0.7 on 2026-08-12 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdr', '0018_sdrsalesfeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='sdroutboundcampaign',
            name='linkedin_invitation_message',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
