# Generated by Django 6.0.7 on 2026-08-12 14:14

import uuid
from datetime import timedelta

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

import sdr.models
from common.rls import get_disable_policy_sql, get_enable_policy_sql

COMPLIANCE_TABLES = (
    "sdr_compliance_settings",
    "sdr_channel_compliance_rule",
    "sdr_compliance_event",
    "sdr_data_provenance",
    "sdr_do_not_contact",
)


def backfill_provenance(apps, schema_editor):
    Org = apps.get_model("common", "Org")
    LeadIntake = apps.get_model("sdr", "LeadIntake")
    SDRDataProvenance = apps.get_model("sdr", "SDRDataProvenance")
    source_methods = {
        "facebook_ad": "inbound_form",
        "website_form": "inbound_form",
        "facebook_messenger": "direct_message",
        "linkedin": "direct_message",
        "email": "inbound_email",
        "api": "provider_api",
        "manual": "manual",
        "outbound": "csv_import",
    }
    uses_postgresql_rls = schema_editor.connection.vendor == "postgresql"
    with schema_editor.connection.cursor() as cursor:
        for org_id in Org.objects.values_list("id", flat=True).iterator(chunk_size=100):
            if uses_postgresql_rls:
                cursor.execute(
                    "SELECT set_config('app.current_org', %s, false)",
                    [str(org_id)],
                )
            batch = []
            for intake in LeadIntake.objects.filter(org_id=org_id).iterator(
                chunk_size=500
            ):
                raw = intake.raw_payload or {}
                batch.append(
                    SDRDataProvenance(
                        org_id=intake.org_id,
                        intake_id=intake.id,
                        collection_method=source_methods.get(intake.source, "other"),
                        source_url=str(raw.get("source_url") or "")[:1000],
                        lawful_basis="unassessed",
                        country_code=str(raw.get("country") or "")
                        .strip()
                        .upper()[:3],
                        allowed_channels=[
                            "email",
                            "whatsapp",
                            "linkedin",
                            "phone",
                        ],
                        retention_until=intake.created_at + timedelta(days=730),
                    )
                )
                if len(batch) == 500:
                    SDRDataProvenance.objects.bulk_create(
                        batch, ignore_conflicts=True
                    )
                    batch = []
            if batch:
                SDRDataProvenance.objects.bulk_create(batch, ignore_conflicts=True)
        if uses_postgresql_rls:
            cursor.execute("SELECT set_config('app.current_org', '', false)")


def enable_compliance_rls(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    with schema_editor.connection.cursor() as cursor:
        for table in COMPLIANCE_TABLES:
            cursor.execute(get_enable_policy_sql(table))


def disable_compliance_rls(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    with schema_editor.connection.cursor() as cursor:
        for table in reversed(COMPLIANCE_TABLES):
            cursor.execute(get_disable_policy_sql(table))


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0029_delete_sessiontoken'),
        ('sdr', '0019_sdroutboundcampaign_linkedin_invitation_message'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sdroutboundprospect',
            name='allowed_channels',
            field=models.JSONField(blank=True, default=sdr.models.default_compliance_channels),
        ),
        migrations.AddField(
            model_name='sdroutboundprospect',
            name='consent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sdroutboundprospect',
            name='consent_evidence',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sdroutboundprospect',
            name='lawful_basis',
            field=models.CharField(choices=[('unassessed', 'Not assessed'), ('consent', 'Consent'), ('legitimate_interest', 'Legitimate interest'), ('contract', 'Contract / pre-contract request'), ('legal_obligation', 'Legal obligation'), ('public_task', 'Public task'), ('vital_interest', 'Vital interest')], default='unassessed', max_length=32),
        ),
        migrations.AddField(
            model_name='sdroutboundprospect',
            name='lawful_basis_notes',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='SDRComplianceSettings',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('enforcement_enabled', models.BooleanField(default=False)),
                ('require_lawful_basis', models.BooleanField(default=True)),
                ('retention_mode', models.CharField(choices=[('disabled', 'Disabled'), ('audit_only', 'Audit only'), ('anonymize_sdr', 'Anonymize SDR-owned data')], default='audit_only', max_length=24)),
                ('retention_days', models.PositiveIntegerField(default=730, validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(3650)])),
                ('deletion_grace_days', models.PositiveSmallIntegerField(default=30, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(365)])),
                ('last_retention_scan_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('org', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sdr_compliance_settings', to='common.org')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
            ],
            options={
                'db_table': 'sdr_compliance_settings',
            },
        ),
        migrations.CreateModel(
            name='SDRChannelComplianceRule',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('country_code', models.CharField(default='*', max_length=3)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('whatsapp', 'WhatsApp'), ('linkedin', 'LinkedIn'), ('phone', 'Phone')], max_length=16)),
                ('is_allowed', models.BooleanField(default=True)),
                ('requires_consent', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('org', models.ForeignKey(help_text='Organization this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='common.org')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
            ],
            options={
                'db_table': 'sdr_channel_compliance_rule',
                'ordering': ('country_code', 'channel'),
                'indexes': [models.Index(fields=['org', 'channel', 'country_code'], name='sdr_rule_channel_country_idx')],
                'constraints': [models.UniqueConstraint(fields=('org', 'country_code', 'channel'), name='unique_sdr_country_channel_rule')],
            },
        ),
        migrations.CreateModel(
            name='SDRComplianceEvent',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('event_type', models.CharField(choices=[('provenance_recorded', 'Provenance recorded'), ('contact_allowed', 'Contact allowed'), ('contact_blocked', 'Contact blocked'), ('dnc_added', 'Do-not-contact added'), ('dnc_released', 'Do-not-contact released'), ('retention_due', 'Retention review due'), ('deletion_requested', 'Deletion requested'), ('deletion_cancelled', 'Deletion request cancelled'), ('anonymized', 'SDR data anonymized')], max_length=32)),
                ('channel', models.CharField(blank=True, choices=[('email', 'Email'), ('whatsapp', 'WhatsApp'), ('linkedin', 'LinkedIn'), ('phone', 'Phone')], max_length=16)),
                ('allowed', models.BooleanField(blank=True, null=True)),
                ('reason', models.CharField(blank=True, max_length=500)),
                ('event_key', models.CharField(max_length=255)),
                ('snapshot', models.JSONField(blank=True, default=dict)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('intake', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compliance_events', to='sdr.leadintake')),
                ('org', models.ForeignKey(help_text='Organization this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='common.org')),
                ('prospect', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compliance_events', to='sdr.sdroutboundprospect')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
            ],
            options={
                'db_table': 'sdr_compliance_event',
                'ordering': ('-occurred_at', '-created_at'),
                'indexes': [models.Index(fields=['org', 'event_type', '-occurred_at'], name='sdr_compliance_event_idx')],
                'constraints': [models.UniqueConstraint(fields=('org', 'event_key'), name='unique_sdr_compliance_event')],
            },
        ),
        migrations.CreateModel(
            name='SDRDataProvenance',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('collection_method', models.CharField(choices=[('inbound_form', 'Inbound form'), ('direct_message', 'Direct message'), ('inbound_email', 'Inbound email'), ('provider_api', 'Provider API'), ('csv_import', 'CSV import'), ('manual', 'Manual entry'), ('other', 'Other')], default='other', max_length=24)),
                ('source_url', models.URLField(blank=True, max_length=1000)),
                ('lawful_basis', models.CharField(choices=[('unassessed', 'Not assessed'), ('consent', 'Consent'), ('legitimate_interest', 'Legitimate interest'), ('contract', 'Contract / pre-contract request'), ('legal_obligation', 'Legal obligation'), ('public_task', 'Public task'), ('vital_interest', 'Vital interest')], default='unassessed', max_length=32)),
                ('lawful_basis_notes', models.TextField(blank=True)),
                ('consent_at', models.DateTimeField(blank=True, null=True)),
                ('consent_evidence', models.TextField(blank=True)),
                ('country_code', models.CharField(blank=True, max_length=3)),
                ('allowed_channels', models.JSONField(blank=True, default=sdr.models.default_compliance_channels)),
                ('retention_until', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('retention_due', 'Retention review due'), ('deletion_requested', 'Deletion requested'), ('anonymized', 'Anonymized')], default='active', max_length=24)),
                ('deletion_requested_at', models.DateTimeField(blank=True, null=True)),
                ('anonymized_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('intake', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='data_provenance', to='sdr.leadintake')),
                ('org', models.ForeignKey(help_text='Organization this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='common.org')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
            ],
            options={
                'db_table': 'sdr_data_provenance',
                'indexes': [models.Index(fields=['org', 'status', 'retention_until'], name='sdr_prov_retention_idx')],
            },
        ),
        migrations.CreateModel(
            name='SDRDoNotContactEntry',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('whatsapp', 'WhatsApp'), ('linkedin', 'LinkedIn'), ('phone', 'Phone')], max_length=16)),
                ('identifier', models.CharField(max_length=1000)),
                ('identifier_hash', models.CharField(max_length=64)),
                ('country_code', models.CharField(blank=True, max_length=3)),
                ('reason', models.CharField(choices=[('unsubscribed', 'Unsubscribed / objected'), ('complaint', 'Complaint'), ('admin', 'Administrator'), ('regulatory', 'Regulatory rule'), ('data_request', 'Data subject request'), ('invalid', 'Invalid contact')], max_length=24)),
                ('source', models.CharField(choices=[('email_suppression', 'Email suppression'), ('provider', 'Provider'), ('admin', 'Administrator'), ('data_subject', 'Data subject'), ('retention', 'Retention workflow'), ('system', 'System')], max_length=24)),
                ('is_active', models.BooleanField(default=True)),
                ('blocked_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('org', models.ForeignKey(help_text='Organization this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='common.org')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
            ],
            options={
                'db_table': 'sdr_do_not_contact',
                'ordering': ('-is_active', '-blocked_at'),
                'indexes': [models.Index(fields=['org', 'channel', 'is_active', 'identifier_hash'], name='sdr_dnc_active_lookup_idx')],
                'constraints': [models.UniqueConstraint(fields=('org', 'channel', 'identifier_hash'), name='unique_sdr_channel_dnc')],
            },
        ),
        migrations.RunPython(backfill_provenance, migrations.RunPython.noop),
        migrations.RunPython(enable_compliance_rls, disable_compliance_rls),
    ]
